hmrc/tai-frontend

app/assets/js/tai.js
Work around for IE behaviour.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10474810/
=> TAI-3766 - Store document.referrer value prior to modifying history state

app/controllers/i18n/TaiLanguageController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/util/TaiConstants.scala, app/views/main.scala.html, conf/application.conf, conf/messages.cy, conf/tai.routes, project/FrontendBuild.scala, test/builders/RequestBuilder.scala, test/controllers/i18n/TaiLanguageControllerSpec.scala
This ticket covers mechanics of toggle only - not the inclusion of Welsh message file.
Language toggle implemented behind a feature toggle.
=> TAI-3664 : Implement English/Welsh language toggle

app/views/incomes/bbsi/update/bank_building_society_update_interest.scala.html, app/views/incomes/bonusPaymentAmount.scala.html, app/views/incomes/payslipAmount.scala.html, app/views/incomes/taxablePayslipAmount.scala.html, test/views/html/incomes/BankBuildingSocietyUpdateInterestSpec.scala
=> Revert "TAI-3699: revert changes"

app/views/includes/ptaHeader.scala.html, app/views/main.scala.html
Steps up the version from 3.0.2 to 3.2.3
Automated & manual/visual inspection carried out - no issues evident.
=> TAI-3769 : Un-pin the version of assets-frontend

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf
correct the configuration to pull the staging s3 path
=> DDCNLS-4408: Update configuration for correct staging path

app/views/estimatedIncomeTax/whyThisIsAnEstimateDesc.scala.html, conf/messages, conf/messages.cy, test/views/html/estimatedIncomeTax/simpleEstimatedIncomeTaxSpec.scala, test/views/html/estimatedIncomeTax/whyThisIsAnEstimateDescSpec.scala, test/views/html/estimatedIncomeTax/zeroTaxEstimatedIncomeTaxSpec.scala
=> ST-197:Fixed bug to use end of current tax year

app/views/taxCodeChange/taxCodeComparison.scala.html, conf/messages, conf/messages.cy, test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
=> ST-115: Add button to tax free account

conf/application.conf
=> ST-115: Toggle tax code change on

app/views/taxCodeChange/yourTaxFreeAmount.scala.html, conf/messages, conf/messages.cy
=> ST-238: removed link from your-tax-free-amount page

app/views/paye/historicPayAsYouEarn.scala.html
=> HOTFIX-tax-year-previous: Remove link from CY-(N) pages.

project/Microservice.scala, project/plugins.sbt
=> update config for new build

app/assets/sass/tai03092018.scss, app/views/incomes/editIncome.scala.html, app/views/incomes/editPension.scala.html
=> ST-297: text box for estimated income resized

app/views/incomes/editPension.scala.html, test/views/html/incomes/EditPensionSpec.scala
=> ST-288-fix: Add employment name to update pension income screen

app/assets/sass/tai03092018.scss, app/views/incomes/bonusPaymentAmount.scala.html, app/views/incomes/calcUnavailable.scala.html, app/views/incomes/confirm_save_Income.scala.html, app/views/incomes/editIncome.scala.html, app/views/incomes/editPension.scala.html, app/views/incomes/editSuccess.scala.html, app/views/incomes/estimatedPay.scala.html
=> ST-296: Remove blue heading from Estimated Pay

app/assets/sass/modules/_text-input.scss, app/assets/sass/tai03092018.scss, app/views/includes/forms/input.scala.html, app/views/incomes/bonusPaymentAmount.scala.html, app/views/incomes/payslipAmount.scala.html, app/views/incomes/taxablePayslipAmount.scala.html
=> ST-298: Update currency text input to include symbol in input

app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala, test/uk/gov/hmrc/tai/model/domain/TaxCodeRecordSpec.scala
=> ST-323: Refactor and add logging

app/views/taxCodeChange/formattedTaxCodeForComparison.scala.html
=> ST-322: adding wrapping for longer payroll numbers

project/FrontendBuild.scala
=> CSP-upgrade: Upgraded csp library version

app/views/incomes/editPension.scala.html
=> Remove terror typo in editPension.scala.html

app/controllers/income/UpdateIncomeNextYearController.scala, app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala, app/uk/gov/hmrc/tai/model/cache/UpdateNextYearsIncomeCacheModel.scala, app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala, app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala, app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala, test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
=> ST-384 Spike

app/uk/gov/hmrc/tai/util/constants/GoogleAnalyticsConstants.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, test/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModelSpec.scala
=> ST-365:Add logging to non mismatch tax codes

app/controllers/income/UpdateIncomeNextYearController.scala
=> Update Next Years controller create preAction

conf/messages, conf/messages.cy
=> ST-396:content change on CY+1/same page cancel link

app/views/includes/compareValueInput.scala.html, test/views/html/incomes/EditIncomeIrregularHoursSpec.scala
=> ST-407: Resolve accessibility problem

app/views/paye/historicPayAsYouEarn.scala.html
=> ST-link: removing link to previous years tax code

test/views/html/paye/historicPayAsYouEarnSpec.scala
=> ST-link: fixing unit test

app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/Main.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
=> ST-418: Add GA Event tags for EstPay CY+1 Journey

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
=> Updated feedback URL

app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/Main.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html
=> ST-418-2: Update CY+1 Estimated Journey after QA

app/controllers/HelpController.scala
=> Added try / catch for failing getEligibilityStatus

app/views/paye/historicPayAsYouEarn.scala.html, test/views/html/paye/historicPayAsYouEarnSpec.scala
=> ST-421: adding link to latest tax code back in

app/assets/sass/tai05102018.scss, app/views/includes/ptaHeader.scala.html, app/views/incomes/bonusPaymentAmount.scala.html, app/views/incomes/bonusPayments.scala.html, app/views/incomes/confirmAmountEntered.scala.html, app/views/incomes/confirm_save_Income.scala.html, app/views/incomes/editIncome.scala.html, app/views/incomes/editIncomeIrregularHours.scala.html, app/views/incomes/editPension.scala.html, app/views/incomes/estimatedPay.scala.html, app/views/incomes/estimatedPayLandingPage.scala.html, app/views/incomes/howToUpdate.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html, app/views/incomes/payPeriod.scala.html, app/views/incomes/payslipAmount.scala.html, app/views/incomes/payslipDeductions.scala.html, app/views/incomes/taxablePayslipAmount.scala.html, app/views/incomes/workingHours.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html
=> ST-416: Update to 2/3 layout

app/controllers/TaxCodeChangeController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/config/wiring.scala, app/uk/gov/hmrc/tai/connectors/CompanyCarConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala, app/uk/gov/hmrc/tai/service/EmploymentService.scala, app/uk/gov/hmrc/tai/service/JourneyCacheService.scala, app/uk/gov/hmrc/tai/service/PersonService.scala, app/uk/gov/hmrc/tai/service/benefits/CompanyCarService.scala, conf/application.conf, conf/tai.routes, test/controllers/TaxCodeChangeControllerSpec.scala
=> ST-447: Changing TaxCodeChangeController to use dependency injection

app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/AuditService.scala, app/uk/gov/hmrc/tai/service/TrackingService.scala, conf/tai.routes, test/controllers/WhatDoYouWantToDoControllerSpec.scala
=> ST-447: WhatDoYouWantToDoController now uses dependency injection

app/controllers/YourIncomeCalculationController.scala, conf/tai.routes, test/controllers/YourIncomeCalculationControllerSpec.scala
=> ST-447: YouIncomeCalculationController now uses dependency injection

app/controllers/AuditController.scala, app/controllers/YourTaxCodeController.scala, conf/tai.routes, test/controllers/AuditControllerSpec.scala, test/controllers/YourTaxCodeControllerSpec.scala
=> Dependency injection for AuditController and YourTaxCodeController

app/views/paye/historicPayAsYouEarn.scala.html, test/views/html/paye/historicPayAsYouEarnSpec.scala
=> ST-421: Remove tax code at the end of the year link

app/controllers/DeceasedController.scala, app/controllers/DetailedIncomeTaxEstimateController.scala, conf/tai.routes, test/controllers/DeceasedControllerSpec.scala, test/controllers/DetailedIncomeTaxEstimateControllerSpec.scala
=> ST-447: Dependency injection for DetailedIncomeTaxEstimateController and DeceasedController

app/controllers/CompanyCarController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/JourneyCacheService.scala, app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala, conf/tai.routes, test/controllers/CompanyCarControllerSpec.scala
=> ST-447b: Updated Company Car Controller to use Dependency Injection.

app/controllers/IncomeController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/tai.routes, test/controllers/IncomeControllerSpec.scala
=> ST-447c: Dependency Injection for IncomeController

app/controllers/PotentialUnderpaymentController.scala, app/controllers/ServiceController.scala, app/controllers/TaxAccountSummaryController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/tai.routes, test/controllers/PotentialUnderpaymentControllerSpec.scala, test/controllers/ServiceControllerSpec.scala, test/controllers/TaxAccountSummaryControllerSpec.scala
=> ST-447: dependency injection for PotentialUnderpaymentController and ServiceController

app/controllers/employments/AddEmploymentController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/TrackingService.scala, conf/tai.routes, test/controllers/employments/AddEmploymentControllerSpec.scala
=> St 447 add employment controller di

app/controllers/benefits/CompanyBenefitController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/tai.routes, test/controllers/benefits/CompanyBenefitControllerSpec.scala
=> ST-477-CompanyCarBenefitController

app/controllers/i18n/TaiLanguageController.scala, app/controllers/income/UpdateIncomeNextYearController.scala, app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, app/controllers/income/previousYears/UpdateIncomeDetailsController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/dev.routes, conf/tai.routes, test/controllers/i18n/TaiLanguageControllerSpec.scala, test/controllers/income/UpdateIncomeNextYearControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala, test/controllers/income/previousYears/UpdateIncomeDetailsControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxCodeDescriptorSpec.scala
=> ST-447 dependency injection for more controllers

app/controllers/pensions/AddPensionProviderController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/PensionProviderService.scala, conf/tai.routes, test/controllers/pensions/AddPensionProviderControllerSpec.scala
=> ST-447: AddPensionProviderController now uses dependency injection

app/controllers/pensions/UpdatePensionProviderController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/tai.routes, test/controllers/pensions/UpdatePensionProviderControllerSpec.scala
=> ST-447: UpdatePensionProviderController now uses dependency injection

app/controllers/employments/UpdateEmploymentController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, conf/tai.routes, test/controllers/employments/UpdateEmploymentControllerSpec.scala
=> ST-447: UpdateEmploymentController now uses dependency injection

app/controllers/income/bbsi/BbsiCloseAccountController.scala, app/controllers/income/bbsi/BbsiController.scala, app/controllers/income/bbsi/BbsiRemoveAccountController.scala, app/controllers/income/bbsi/BbsiUpdateAccountController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/BbsiService.scala, test/controllers/income/bbsi/BbsiCloseAccountControllerSpec.scala, test/controllers/income/bbsi/BbsiControllerSpec.scala, test/controllers/income/bbsi/BbsiRemoveAccountControllerSpec.scala, test/controllers/income/bbsi/BbsiUpdateAccountControllerSpec.scala, test/uk/gov/hmrc/tai/service/BbsiServiceSpec.scala
=> ST-447: BbsiService now uses dependency injection

app/controllers/CompanyCarController.scala, app/controllers/ExternalServiceRedirectController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/SessionService.scala, test/controllers/CompanyCarControllerSpec.scala, test/controllers/ExternalServiceRedirectControllerSpec.scala, test/uk/gov/hmrc/tai/service/SessionServiceSpec.scala
=> ST-447: SessionService now uses dependency injection

app/uk/gov/hmrc/tai/service/TaxPeriodLabelService.scala, test/controllers/PayeControllerHistoricSpec.scala, test/uk/gov/hmrc/tai/service/TaxPeriodLabelServiceSpec.scala, test/views/html/paye/historicPayAsYouEarnSpec.scala
=> ST-447: TaxPeriodLabelService is now an object

app/controllers/income/UpdateIncomeNextYearController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala, test/controllers/income/UpdateIncomeNextYearControllerSpec.scala, test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
=> ST-447 UpdateNextYearsIncomeService now uses dependency injection

app/controllers/CompanyCarController.scala, app/controllers/TaxCodeChangeController.scala, app/controllers/TaxFreeAmountController.scala, app/controllers/UnderpaymentFromPreviousYearController.scala, app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/service/benefits/CompanyCarService.scala, test/controllers/CompanyCarControllerSpec.scala, test/controllers/TaxCodeChangeControllerSpec.scala, test/controllers/TaxFreeAmountControllerSpec.scala, test/uk/gov/hmrc/tai/service/benefits/CompanyCarServiceSpec.scala
=> St 447 - Company car service now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala, app/uk/gov/hmrc/tai/service/BbsiService.scala, test/uk/gov/hmrc/tai/connectors/BbsiConnectorSpec.scala, test/uk/gov/hmrc/tai/service/BbsiServiceSpec.scala
=> ST-447: BbsiConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/PensionProviderConnector.scala, app/uk/gov/hmrc/tai/service/PensionProviderService.scala, test/uk/gov/hmrc/tai/connectors/PensionProviderConnectorSpec.scala
=> ST-447: PensionProviderConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/PersonConnector.scala, app/uk/gov/hmrc/tai/service/PersonService.scala, test/uk/gov/hmrc/tai/connectors/PersonConnectorSpec.scala, test/uk/gov/hmrc/tai/service/PersonServiceSpec.scala
=> ST-447: PersonConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/PreviousYearsIncomeConnector.scala, app/uk/gov/hmrc/tai/service/PreviousYearsIncomeService.scala, test/uk/gov/hmrc/tai/connectors/PreviousYearsIncomeConnectorSpec.scala
=> ST-447: PreviousYeardsIncomeConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/SessionConnector.scala, app/uk/gov/hmrc/tai/service/SessionService.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/SessionConnectorSpec.scala
=> ST-447: SessionConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/service/CodingComponentService.scala, app/uk/gov/hmrc/tai/service/TaxAccountService.scala, test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala, test/uk/gov/hmrc/tai/service/CodingComponentServiceSpec.scala, test/uk/gov/hmrc/tai/service/TaxAccountServiceSpec.scala
=> ST-447: TaxAccountConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala, app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala, test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala, test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
=> ST-447: TaxCodeChangeConnector now uses dependency injection

app/views/pensions/update/doYouGetThisPensionIncome.scala.html, test/views/html/employments/UpdateRemoveEmploymentDecisionSpec.scala, test/views/html/pensions/DoYouGetThisPensionIncomePageSpec.scala
=> Hard coded urls

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/TrackingConnector.scala, app/uk/gov/hmrc/tai/service/TrackingService.scala, test/uk/gov/hmrc/tai/connectors/TrackingConnectorSpec.scala, test/uk/gov/hmrc/tai/service/TrackingServiceSpec.scala
=> ST-446: TrackingConnector now uses dependency injection

app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCache.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/JourneyCacheConnectorSpec.scala
=> ST-447: JourneyCacheConnector now uses dependency injection

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala, app/uk/gov/hmrc/tai/connectors/BenefitsConnector.scala, app/uk/gov/hmrc/tai/connectors/CompanyCarConnector.scala, app/uk/gov/hmrc/tai/connectors/EmploymentsConnector.scala, app/uk/gov/hmrc/tai/connectors/HttpHandler.scala, app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala, app/uk/gov/hmrc/tai/connectors/PensionProviderConnector.scala, app/uk/gov/hmrc/tai/connectors/PersonConnector.scala, app/uk/gov/hmrc/tai/connectors/PreviousYearsIncomeConnector.scala, app/uk/gov/hmrc/tai/connectors/SessionConnector.scala, app/uk/gov/hmrc/tai/connectors/TaiConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala, app/uk/gov/hmrc/tai/connectors/TrackingConnector.scala, app/uk/gov/hmrc/tai/connectors/UserDetailsConnector.scala, app/uk/gov/hmrc/tai/service/IncomeService.scala, app/uk/gov/hmrc/tai/service/PersonService.scala, test/controllers/ServiceControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala, test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/UserDetailsConnectorSpec.scala, test/uk/gov/hmrc/tai/service/PersonServiceSpec.scala
=> ST-447: TaiConnector now uses dependency injection

app/controllers/AuditController.scala, test/controllers/AuditControllerSpec.scala, test/controllers/TaxCodeChangeControllerSpec.scala
=> ST-475: AuditController updated to use new auth

app/controllers/YourTaxCodeController.scala, app/views/taxCodeDetails.scala.html, app/views/taxCodeDetailsPreviousYears.scala.html, test/controllers/YourTaxCodeControllerSpec.scala, test/views/html/TaxCodeDetailsViewSpec.scala
=> ST-475-AuthUpgrade-saUtr

test/builders/UserBuilder.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala, test/views/html/TaxCodeDetailsViewSpec.scala
=> ST-475-ViewSpec

app/controllers/AuditController.scala, app/controllers/CompanyCarController.scala, app/views/benefits/updateCompanyCar.scala.html, test/controllers/CompanyCarControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/SessionConnectorSpec.scala, test/views/html/TaxCodeDetailsViewSpec.scala
=> ST-475: Company car controller now uses new auth

app/controllers/YourIncomeCalculationController.scala, app/views/incomes/historicIncomeCalculation.scala.html, app/views/incomes/yourIncomeCalculation.scala.html, app/views/print/historicIncomeCalculation.scala.html, app/views/print/yourIncomeCalculation.scala.html, test/controllers/YourIncomeCalculationControllerSpec.scala
=> ST-475-YourIncomeCalculation

app/controllers/YourIncomeCalculationController.scala, test/controllers/YourIncomeCalculationControllerSpec.scala
=> Removed unused params

app/controllers/UnderpaymentFromPreviousYearController.scala, app/views/previousYearUnderpayment.scala.html, test/controllers/UnderpaymentFromPreviousYearControllerSpec.scala, test/controllers/YourIncomeCalculationControllerSpec.scala
=> St 475 underpayment from previous year controller

app/controllers/CompanyCarController.scala, app/controllers/actions/DeceasedActionFilter.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/model/domain/Person.scala, test/controllers/CompanyCarControllerSpec.scala, test/controllers/actions/DeceasedActionFilterSpec.scala, test/controllers/actions/FakeDeceasedActionFilter.scala, test/controllers/auth/AuthActionSpec.scala
=> ST-475: splitting out new action to check if person is deceased

app/controllers/AuditController.scala, app/controllers/CompanyCarController.scala, app/controllers/TaxAccountSummaryController.scala, app/controllers/TaxCodeChangeController.scala, app/controllers/UnderpaymentFromPreviousYearController.scala, app/controllers/YourIncomeCalculationController.scala, app/controllers/YourTaxCodeController.scala, test/controllers/AuditControllerSpec.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/controllers/TaxCodeChangeControllerSpec.scala, test/controllers/UnderpaymentFromPreviousYearControllerSpec.scala, test/controllers/YourIncomeCalculationControllerSpec.scala, test/controllers/YourTaxCodeControllerSpec.scala
=> ST-475: updating new auth controllers to use deceasedFilter

app/controllers/DeceasedController.scala, app/views/deceased_helpline.scala.html, test/controllers/DeceasedControllerSpec.scala, test/views/html/deceasedHelplinePageSpec.scala
=> ST-475: updating DeceasedController to use new auth

app/uk/gov/hmrc/tai/config/TaiModule.scala, app/uk/gov/hmrc/tai/connectors/AuthClientAuthConnector.scala, conf/application.conf
=> Fix AuthClientAuthConnector (lazy val)

test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
=> Fix falseyness

app/controllers/actions/DeceasedActionFilter.scala, test/controllers/actions/DeceasedActionFilterSpec.scala, test/controllers/actions/FakeDeceasedActionFilter.scala
=> Add deceased action filter ready for new auth

app/controllers/TestAuthController.scala, app/controllers/actions/DeceasedActionFilter.scala, app/views/authCheck.scala.html, app/views/main.scala.html, conf/tai.routes
=> Add test auth endpoint that connects to new auth

app/controllers/income/UpdateIncomeNextYearController.scala, app/uk/gov/hmrc/tai/util/MapForGoogleAnalytics.scala, app/uk/gov/hmrc/tai/util/MonetaryUtil.scala, app/uk/gov/hmrc/tai/util/constants/GoogleAnalyticsConstants.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, app/uk/gov/hmrc/tai/viewModels/income/ConfirmAmountEnteredViewModel.scala, app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html, test/controllers/income/UpdateIncomeNextYearControllerSpec.scala, test/uk/gov/hmrc/tai/util/MonetaryUtilSpec.scala, test/uk/gov/hmrc/tai/viewModels/income/ConfirmAmountEnteredViewModelSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1Confirm.scala
=> ST-432: GA Custom Dimension estimated pay CY+1

app/controllers/auth/AuthAction.scala, test/controllers/auth/AuthActionSpec.scala
=> Auth - Remove AffinityGroup to allow verify users

app/controllers/TestAuthController.scala, app/controllers/actions/ValidatePerson.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/model/domain/Person.scala, test/controllers/actions/FakeValidatePerson.scala, test/controllers/actions/ValidatePersonSpec.scala, test/controllers/auth/AuthActionSpec.scala
=> ST-475-AuthUpgrade- Renamed person filter and removed the person checks from auth action

conf/dev.routes, conf/tai.routes
=> Moved update income tax for CY+1 routes to prod

conf/tai.routes
=> Fix unauthorised route

app/controllers/AuditController.scala, test/controllers/AuditControllerSpec.scala
=> AuthUprade - Convert AuthController to new auth

app/controllers/CompanyCarController.scala, app/views/benefits/updateCompanyCar.scala.html, test/controllers/CompanyCarControllerSpec.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala
=> AuthUpgrade - Convert Company Car Controller

app/controllers/DeceasedController.scala, app/views/deceased_helpline.scala.html, test/controllers/DeceasedControllerSpec.scala, test/views/html/deceasedHelplinePageSpec.scala
=> AuthUpgrade - Deceased Controller

app/controllers/DetailedIncomeTaxEstimateController.scala, app/views/estimatedIncomeTax/detailedIncomeTaxEstimate.scala.html, test/controllers/DetailedIncomeTaxEstimateControllerSpec.scala
=> Auth Upgrade - DetailedIncomeTaxEstimateController

conf/tai.routes
=> Correct routes for estimated pay CY+1

app/controllers/EstimatedIncomeTaxController.scala, app/views/estimatedIncomeTax/complexEstimatedIncomeTax.scala.html, app/views/estimatedIncomeTax/noCurrentIncome.scala.html, app/views/estimatedIncomeTax/simpleEstimatedIncomeTax.scala.html, app/views/estimatedIncomeTax/zeroTaxEstimatedIncomeTax.scala.html, test/controllers/EstimatedIncomeTaxControllerSpec.scala
=> AuthUpgrade - Estimated Income Tax Controller

app/controllers/YourTaxCodeController.scala, app/views/taxCodeDetails.scala.html, app/views/taxCodeDetailsPreviousYears.scala.html
=> New authed YourTaxCodeController

app/controllers/DetailedIncomeTaxEstimateController.scala, app/controllers/ErrorPagesHandler.scala, app/controllers/EstimatedIncomeTaxController.scala, conf/application.conf, test/controllers/ErrorPagesHandlerSpec.scala
=> Extracted log and internal server error to a function

app/controllers/YourIncomeCalculationController.scala, app/controllers/YourTaxCodeController.scala, app/views/incomes/historicIncomeCalculation.scala.html, app/views/incomes/yourIncomeCalculation.scala.html, app/views/print/historicIncomeCalculation.scala.html, app/views/print/yourIncomeCalculation.scala.html, test/controllers/YourIncomeCalculationControllerSpec.scala, test/controllers/YourTaxCodeControllerSpec.scala
…oller to handle generic errors
=> New authed YourIncomeCalculationController

app/controllers/ExternalServiceRedirectController.scala, app/controllers/HelpController.scala, app/controllers/YourTaxCodeController.scala, app/views/help/getHelp.scala.html, test/controllers/ExternalServiceRedirectControllerSpec.scala, test/controllers/HelpControllerSpec.scala, test/controllers/YourTaxCodeControllerSpec.scala, test/views/html/getHelpPageSpec.scala
=> AuthUpgrade - ExternalService, Help and YourTaxCode controller

app/controllers/ErrorPagesHandler.scala, app/controllers/PayeControllerHistoric.scala, app/controllers/WhatDoYouWantToDoController.scala, app/views/paye/historicPayAsYouEarn.scala.html, app/views/whatDoYouWantToDoTileView.scala.html, test/controllers/ErrorPagesHandlerSpec.scala, test/controllers/FakeAuthAction.scala, test/controllers/PayeControllerHistoricSpec.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala
=> New authed PayeControllerHistoric and WhatDoYouWantToDo controllers

app/controllers/ErrorPagesHandler.scala, app/controllers/ServiceController.scala, app/controllers/TaxAccountSummaryController.scala, app/controllers/TaxCodeChangeController.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/connectors/UserDetailsConnector.scala, app/views/incomeTaxSummary.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, app/views/taxCodeChange/whatHappensNext.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, test/builders/UserBuilder.scala, test/controllers/ControllerViewTestHelper.scala, test/controllers/ErrorPagesHandlerSpec.scala, test/controllers/FakeAuthAction.scala, test/controllers/ServiceControllerSpec.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/controllers/TaxCodeChangeControllerSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala, test/views/html/getHelpPageSpec.scala
=> Auth tax free amount

app/controllers/UnauthorisedController.scala, app/controllers/auth/AuthAction.scala, conf/tai.routes, test/controllers/UnauthorisedControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala
=> New auth redirects to login page

app/controllers/auth/AuthAction.scala, app/views/main.scala.html, test/builders/UserBuilder.scala, test/controllers/FakeAuthAction.scala
=> Added confidence level to new auth

app/controllers/benefits/CompanyBenefitController.scala, app/controllers/benefits/RemoveCompanyBenefitController.scala, app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/controllers/employments/UpdateEmploymentController.scala, app/controllers/income/previousYears/UpdateIncomeDetailsController.scala, app/controllers/pensions/AddPensionProviderController.scala, app/controllers/pensions/UpdatePensionProviderController.scala, app/views/benefits/removeBenefitTotalValue.scala.html, app/views/benefits/removeCompanyBenefitCheckYourAnswers.scala.html, app/views/benefits/removeCompanyBenefitConfirmation.scala.html, app/views/benefits/removeCompanyBenefitStopDate.scala.html, app/views/benefits/updateOrRemoveCompanyBenefitDecision.scala.html, app/views/can_we_contact_by_phone.scala.html, test/controllers/benefits/CompanyBenefitControllerSpec.scala, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala, test/views/html/CanWeContactByPhoneSpec.scala
=> Authed up benefits controllers

app/controllers/IncomeSourceSummaryController.scala, app/controllers/IncomeTaxComparisonController.scala, app/controllers/NoCYIncomeTaxErrorController.scala, app/views/IncomeSourceSummary.scala.html, app/views/incomeTaxComparison/Main.scala.html, app/views/noCYIncomeTaxErrorPage.scala.html, test/controllers/IncomeSourceSummaryControllerSpec.scala, test/controllers/IncomeTaxComparisonControllerSpec.scala, test/controllers/NoCYIncomeTaxErrorControllerSpec.scala
=> Authed NoCYIncomeTaxError, IncomeTaxComparison and IncomeSourceSummary controllers

app/controllers/pensions/UpdatePensionProviderController.scala, app/views/pensions/update/confirmation.scala.html, app/views/pensions/update/doYouGetThisPensionIncome.scala.html, app/views/pensions/update/updatePensionCheckYourAnswers.scala.html, app/views/pensions/update/whatDoYouWantToTellUs.scala.html, test/controllers/pensions/UpdatePensionProviderControllerSpec.scala
=> Authed UpdatePensionProviderController

app/controllers/pensions/UpdatePensionProviderController.scala
=> Fixed a failing spec

app/controllers/pensions/AddPensionProviderController.scala, app/views/pensions/addPensionCheckYourAnswers.scala.html, app/views/pensions/addPensionConfirmation.scala.html, app/views/pensions/addPensionErrorPage.scala.html, app/views/pensions/addPensionName.scala.html, app/views/pensions/addPensionNumber.scala.html, app/views/pensions/addPensionReceivedFirstPay.scala.html, app/views/pensions/addPensionStartDate.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala
=> Authed add pension provider controller

app/controllers/income/UpdateIncomeNextYearController.scala, app/views/incomes/nextYear/updateIncomeCYPlus1Confirm.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Same.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Start.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Success.scala.html, app/views/incomes/nextYear/updateIncomeCYPlus1Template.scala.html, test/controllers/income/UpdateIncomeNextYearControllerSpec.scala
=> Authed upgrade to update CY+1 income

app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/controllers/employments/UpdateEmploymentController.scala, app/views/employments/add_employment_error_page.scala.html, app/views/employments/add_employment_first_pay_form.scala.html, app/views/employments/add_employment_name_form.scala.html, app/views/employments/add_employment_payroll_number_form.scala.html, app/views/employments/add_employment_start_date_form.scala.html, app/views/employments/confirmation.scala.html, app/views/incomes/addIncomeCheckYourAnswers.scala.html, test/controllers/employments/AddEmploymentControllerSpec.scala
=> ST-475 Auth update for AddEmploymentController

app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/views/employments/EndEmploymentIrregularPaymentError.scala.html, app/views/employments/endEmployment.scala.html, app/views/employments/endEmploymentWithinSixWeeksError.scala.html, app/views/employments/update_remove_employment_decision.scala.html, test/controllers/employments/AddEmploymentControllerSpec.scala, test/controllers/employments/EndEmploymentControllerSpec.scala
=> ST-475 end employment controller AUTH update

app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/views/employments/EndEmploymentIrregularPaymentError.scala.html, app/views/employments/endEmployment.scala.html, app/views/employments/endEmploymentWithinSixWeeksError.scala.html, app/views/employments/update_remove_employment_decision.scala.html, test/controllers/employments/AddEmploymentControllerSpec.scala, test/controllers/employments/EndEmploymentControllerSpec.scala
=> Revert "ST-475 end employment controller AUTH update"

app/controllers/auth/AuthAction.scala, test/controllers/auth/AuthActionSpec.scala
=> Fix unauthorised redirect for all exceptions

app/controllers/UnderpaymentFromPreviousYearController.scala, app/views/previousYearUnderpayment.scala.html, test/controllers/UnderpaymentFromPreviousYearControllerSpec.scala
=> Authed UnderpaymentFromPreviousYearController

app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/views/employments/EndEmploymentIrregularPaymentError.scala.html, app/views/employments/endEmployment.scala.html, app/views/employments/endEmploymentWithinSixWeeksError.scala.html, app/views/employments/update_remove_employment_decision.scala.html, test/controllers/employments/EndEmploymentControllerSpec.scala
=> AuthUpgrade - End Employment

app/controllers/UnauthorisedController.scala, app/controllers/auth/AuthAction.scala, conf/tai.routes, test/controllers/UnauthorisedControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala
=> ST-523: Distinguish between verify and GG users for auth

app/controllers/TaxAccountSummaryController.scala, app/views/incomeTaxSummary.scala.html, test/controllers/TaxAccountSummaryControllerSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala
=> revert TaxAccountSummaryController to use old auth so users can log in via verify

app/views/potentialUnderpayment.scala.html
=> ST-503: Updated view to show pence in IYA CY amount

app/controllers/UnauthorisedController.scala, app/controllers/auth/AuthAction.scala, conf/tai.routes, test/controllers/UnauthorisedControllerSpec.scala
=> ST-544-Redirect low confidence level users to failed uplift Url

app/views/includes/confirmationSuccessBanner.scala.html
=> ST-535 Prettify confirmation banner

app/controllers/employments/EndEmploymentController.scala, app/uk/gov/hmrc/tai/viewModels/employments/UpdateEmploymentCheckYourAnswersViewModel.scala, app/views/IncomeSourceSummary.scala.html, app/views/incomes/estimatedPayLandingPage.scala.html, conf/tai.routes, test/controllers/employments/EndEmploymentControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/employments/UpdateEmploymentCheckYourAnswersViewModelSpec.scala, test/views/html/IncomeSourceSummaryViewSpec.scala, test/views/html/incomes/EstimatedPayLandingPageSpec.scala
Merge these as well:
https://github.com/hmrc/tai-acceptance-test-suite/pull/124 
https://github.com/hmrc/tai-performance-test-suite/pull/18
=> Refactor employment journey redirect

app/views/main.scala.html
=> Mtach up scss file name

app/uk/gov/hmrc/tai/config/wiring.scala, app/uk/gov/hmrc/tai/connectors/AuthClientAuthConnector.scala, project/FrontendBuild.scala, project/plugins.sbt
=> Dep-Upgrade: Updated library dependencies to latest version

app/controllers/employments/EndEmploymentController.scala, app/uk/gov/hmrc/tai/viewModels/employments/UpdateEmploymentCheckYourAnswersViewModel.scala, app/views/IncomeSourceSummary.scala.html, app/views/incomes/estimatedPayLandingPage.scala.html, conf/tai.routes, test/controllers/employments/EndEmploymentControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/employments/UpdateEmploymentCheckYourAnswersViewModelSpec.scala, test/views/html/IncomeSourceSummaryViewSpec.scala, test/views/html/incomes/EstimatedPayLandingPageSpec.scala
=> ST-487-End employment redirect

app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
=> ST-430: fixed confirmIncomeIrregularHours to make NewAmountKey optional

app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
=> Revert "ST-430: fixed confirmIncomeIrregularHours to make NewAmountKey optional"

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf
=> ConfirmedToggle:Implemented toggle for hypothetical fix

app/assets/js/urbanner.js, app/assets/sass/tai11022019.scss, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/main.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/mocks/MockTemplateRenderer.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
- [ yes] Unit tests passing
- [ yes] Coverage reached
- [ yes] Acceptance tests passing
- [ no] Reviewed
=> Ddcnls 5481

app/assets/js/urbanner.js, app/assets/sass/tai11022019.scss, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/main.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/mocks/MockTemplateRenderer.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> Revert "Ddcnls 5481"

app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, app/views/whatDoYouWantToDoTileView.scala.html, test/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModelSpec.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> ST-550:Confirmed API placed around banner on whatYouWantToDoPage

test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> Fixed DDCNLS-5481 build

app/controllers/IncomeTaxComparisonController.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceComparisonViewModel.scala, app/views/incomeTaxComparison/IncomeSummary.scala.html, conf/application.conf, test/controllers/IncomeTaxComparisonControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeSourceComparisonViewModelSpec.scala
=> ST-557: Cater for CY+1 lack of employment payload

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf
=> Update URBanner url and config

app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala
Acceptance test branch DDCNOS-4374 to be merged alongside this change.
=> removes bbsi and untaxed interest from summary view and tweaks tests

app/views/incomeTaxComparison/TaxCodes.scala.html
=> ST-561: Resolve table styling bug

app/uk/gov/hmrc/tai/service/TrackingService.scala, conf/application.conf, test/uk/gov/hmrc/tai/service/TrackingServiceSpec.scala
=> fixBanner: Filtered out 48 hour journey from banner logic

conf/application.conf
=> Turn tai.confirmedAPI.enabled off

conf/application.conf
Related acc:
https://github.com/hmrc/tai-acceptance-test-suite/pull/132
=> ST-569 Turn ConfirmedAPI on

conf/application.conf
=> Update application.conf - cy plus one toggle

test/views/html/incomes/BonusPaymentsAmountSpec.scala, test/views/html/incomes/BonusPaymentsSpec.scala
=> Updated bonus payments specs

app/controllers/TaxCodeChangeController.scala, app/uk/gov/hmrc/tai/service/yourTaxFreeAmount/TaxCodeChangeReasonsService.scala, app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasons.scala, app/uk/gov/hmrc/tai/util/yourTaxFreeAmount/TaxAmountDueFromUnderpayment.scala, app/uk/gov/hmrc/tai/viewModels/PreviousYearUnderpaymentViewModel.scala, test/controllers/TaxCodeChangeControllerSpec.scala, test/uk/gov/hmrc/tai/service/yourTaxFreeAmount/TaxCodeChangeReasonsServiceSpec.scala, test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/IabdTaxCodeChangeReasonsSpec.scala, test/uk/gov/hmrc/tai/util/yourTaxFreeAmount/TaxAmountDueFromUnderpaymentSpec.scala
stubs data: https://github.com/hmrc/tai-stubs/pull/58
=> ST-572 Update IYA and underpayment dynamic text to show amount of tax owed

app/views/main.scala.html
=> ST-573: Sign out url now shows for new auth pages

app/views/IncomeSourceSummary.scala.html
=> ST 566 Fix a screen reader link

conf/messages, conf/messages.cy
=> ST-453:Updated error messages full year and irregular

conf/messages, conf/messages.cy
=> ST-458: Updated error message gross pay invalid format

app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html, app/views/employments/update/whatDoYouWantToTellUs.scala.html, app/views/employments/update_remove_employment_decision.scala.html, app/views/incomes/editPensionSuccess.scala.html, app/views/pensions/update/doYouGetThisPensionIncome.scala.html, app/views/pensions/update/whatDoYouWantToTellUs.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
=> ST-508-2: Wrap around main headings

conf/messages.cy
=> Fixed unescaped chars in Welsh

app/views/IncomeSourceSummary.scala.html
=> ST-508-2:Wrap around main heading

conf/messages, conf/messages.cy
=> Revert "ST-453:Updated error messages full year and irregular"

app/assets/sass/tai19032019.scss, app/views/employments/update/UpdateEmploymentCheckYourAnswers.scala.html, app/views/employments/update/whatDoYouWantToTellUs.scala.html, app/views/employments/update_remove_employment_decision.scala.html, app/views/incomes/editPensionSuccess.scala.html, app/views/main.scala.html, app/views/pensions/update/doYouGetThisPensionIncome.scala.html, app/views/pensions/update/whatDoYouWantToTellUs.scala.html
=> Banner overflow fix

app/controllers/IncomeTaxComparisonController.scala, app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/service/TrackingService.scala, app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala, app/uk/gov/hmrc/tai/util/constants/journeyCache/UpdateNextYearsIncomeConstants.scala, app/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeTaxComparisonViewModel.scala, app/views/incomeTaxComparison/Main.scala.html, conf/messages, conf/messages.cy, test/controllers/IncomeTaxComparisonControllerSpec.scala, test/uk/gov/hmrc/tai/service/TrackingServiceSpec.scala, test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeTaxComparisonViewModelSpec.scala, test/views/html/incomeTaxComparison/MainSpec.scala
=> ST-588 CY+1 banner

app/controllers/WhatDoYouWantToDoController.scala
=> Logging for what do you want to do controller

app/views/IncomeSourceSummary.scala.html, app/views/incomes/estimatedPayLandingPage.scala.html
=> ST-497: Add GA event tags to links on IncomeSourceSummary page

app/views/IncomeSourceSummary.scala.html, app/views/incomes/estimatedPayLandingPage.scala.html
=>  ST-498: Add GA event tagging for Estimated Pay Landing Page

conf/messages.cy
=> ST-299: removed fullstop from welsh translation as requested

app/views/incomes/howToUpdate.scala.html
=> ST-499: Add GA Tagging for Estimated Pay HowToUpdate page

app/views/incomes/workingHours.scala.html
=> ST-500: Add GA Tagging for Update Estimated Pay your working hours page

app/views/incomes/editIncome.scala.html
=> ST-501: Add GA Tagging for edit annual income page

app/views/incomes/editIncomeIrregularHours.scala.html
=> ST-502: Add GA Tagging for edit income irregular hours page

app/views/incomeTaxSummary_incomeSourceDetail.scala.html
=> Fix long payroll numbers overlapping other content

app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/TaxCodes.scala.html
=> ST-594 Long names in CY+1 tables now carry over

app/views/main.scala.html, conf/application.conf, project/FrontendBuild.scala
=> ST-480: Google tag manager implementation

app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, app/uk/gov/hmrc/tai/forms/IncomeCalculatorForm.scala, app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DynamicPayPeriodTitle.scala, app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/PaySlipAmountViewModel.scala, test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DynamicPayPeriodTitleSpec.scala, test/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/TaxablePaySlipAmountViewModelSpec.scala, test/views/html/incomes/TaxablePaySlipAmountSpec.scala
=> ST-459: Added dynamic messages for taxable pay

app/controllers/WebchatController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/webchat.scala.html, conf/application.conf, conf/tai.routes
=> ST-617: Implement POC for webchat

app/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModel.scala, test/uk/gov/hmrc/tai/viewModels/PotentialUnderpaymentViewModelSpec.scala
=> ST-578: Updated link on Underpayment estimate page

app/assets/sass/modules/tax_code_change.scss
=> ST-574: Fixed padding on bullet points

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
=> Turn cyPlusOneEnabled back to a toggle

conf/application.conf
=> ST 617 Add nuance.com (webchat) through our content security policy

app/controllers/IncomeController.scala, app/uk/gov/hmrc/tai/viewModels/SameEstimatedPayViewModel.scala, app/views/incomes/sameEstimatedPay.scala.html, test/controllers/IncomeControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/SameEstimatedPayViewModelSpec.scala, test/views/html/incomes/SameEstimatedPaySpec.scala
=> ST-616 Return to link

app/controllers/benefits/CompanyBenefitController.scala, app/controllers/benefits/RemoveCompanyBenefitController.scala, app/uk/gov/hmrc/tai/forms/benefits/UpdateOrRemoveCompanyBenefitDecisionForm.scala, conf/tai.routes, test/controllers/benefits/CompanyBenefitControllerSpec.scala, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala
=> ST-595 prepopulate end benefits

app/views/whatDoYouWantToDoTileView.scala.html
=> ST-579:changed the styling of the tax code change tile

app/views/incomes/nextYear/updateIncomeCYPlus1Edit.scala.html
=> ST-465 CY+1 estimated income content changes

app/views/webchat.scala.html
=> Remove div content of webchat

app/assets/js/gtm.js, app/views/main.scala.html
=> ST-621: GTM tagging

app/assets/sass/tai19032019.scss, app/controllers/TaxAccountSummaryController.scala, app/controllers/TaxCodeChangeController.scala, app/controllers/YourTaxCodeController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/incomeTaxSummary.scala.html, app/views/main.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, app/views/taxCodeDetails.scala.html, app/views/webchat.scala.html, conf/application.conf, test/controllers/TaxCodeChangeControllerSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala, test/views/html/TaxCodeDetailsViewSpec.scala, test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala, test/views/html/taxCodeChange/YourTaxFreeAmountViewSpec.scala
=> Feature toggle webchat, anchor webchat on TCC page, persist webchat across pages

test/controllers/TaxCodeChangeControllerSpec.scala
=> stubbed webchat to fix build

app/views/incomeTaxSummary.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, app/views/taxCodeDetails.scala.html
=> reposition webchat to bottom right of grid columns

app/views/webchat.scala.html
=> Webchat desktop only

app/assets/sass/tai19032019.scss, app/views/taxCodeChange/yourTaxFreeAmount.scala.html
=> column-two-thirds on the your tax free amount page

app/views/main.scala.html
=> populate nuance data with session id

conf/messages, conf/messages.cy
=> ST-467-2: Update cancel link content

app/views/main.scala.html
=> Readded Nuance webchat injected script

app/views/main.scala.html
=> Revert "Readded Nuance webchat injected script"

app/views/main.scala.html, conf/application.conf
=> Add toggle to webchat script

app/controllers/WebchatController.scala, app/views/webchat.scala.html, app/views/webchatPoc.scala.html, conf/application.conf, conf/tai.routes
=> restore webchat poc

app/views/main.scala.html, app/views/webchat.scala.html, app/views/webchatPoc.scala.html
=> Put script at the bottom of the page

app/views/main.scala.html
=> ST-632: Remove duplicate gtm tag

app/views/incomeTaxSummary.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, app/views/taxCodeDetails.scala.html
=> webchat-poc: Remove section class from webchat

app/views/main.scala.html
=> Add id to webchat script

project/FrontendBuild.scala
=> DepUpgrade: Upgraded hmrctest to 3.8.0 as this was missed previously

app/views/incomeTaxSummary.scala.html, app/views/main.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, app/views/taxCodeDetails.scala.html, conf/application.conf
=> Remove webchat from target pages

app/controllers/IncomeSourceSummaryController.scala, app/views/IncomeSourceSummary.scala.html, test/controllers/IncomeSourceSummaryControllerSpec.scala
=> Reverted income source to legacy auth

app/controllers/TaxAccountSummaryController.scala, app/uk/gov/hmrc/tai/connectors/EmploymentsConnector.scala, app/uk/gov/hmrc/tai/connectors/PersonConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/model/domain/TaxComponentType.scala, app/uk/gov/hmrc/tai/model/domain/TaxFreeAmountComparison.scala, app/uk/gov/hmrc/tai/model/domain/TaxedIncome.scala, app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala, app/uk/gov/hmrc/tai/model/domain/tracking/formatter/TrackedFormFormatters.scala, app/uk/gov/hmrc/tai/service/EmploymentService.scala, app/uk/gov/hmrc/tai/service/IncomeService.scala, app/uk/gov/hmrc/tai/service/TaxAccountService.scala, app/uk/gov/hmrc/tai/service/TaxAccountSummaryService.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceViewModel.scala, app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/EmploymentsConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/SessionConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala, test/uk/gov/hmrc/tai/model/domain/TaxCodeIncomeSpec.scala, test/uk/gov/hmrc/tai/model/domain/TaxComponentTypeSpec.scala, test/uk/gov/hmrc/tai/model/domain/income/NonTaxCodeIncomeComponentTypeSpec.scala, test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala, test/uk/gov/hmrc/tai/service/TaxAccountSummaryServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala, test/utils/TaxAccountSummaryTestData.scala
=> Revert "Revert "[NGC-4566] - Move taxCodeIncomes and employments to tai""

app/uk/gov/hmrc/tai/viewModels/estimatedIncomeTax/ComplexEstimatedIncomeTaxViewModel.scala, app/uk/gov/hmrc/tai/viewModels/estimatedIncomeTax/EstimatedIncomeViewModel.scala, app/uk/gov/hmrc/tai/viewModels/estimatedIncomeTax/ZeroTaxEstimatedIncomeTaxViewModel.scala, test/uk/gov/hmrc/tai/viewModels/estimatedIncomeTax/EstimatedIncomeViewModelSpec.scala
=> get-removal: removal of Option.get from code

app/controllers/auth/WithAuthorisedForTai.scala, conf/application-json-logger.xml, conf/logback.xml
=> Logging for play auth

app/controllers/TaxAccountSummaryController.scala, app/uk/gov/hmrc/tai/connectors/EmploymentsConnector.scala, app/uk/gov/hmrc/tai/connectors/PersonConnector.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/model/domain/TaxComponentType.scala, app/uk/gov/hmrc/tai/model/domain/TaxFreeAmountComparison.scala, app/uk/gov/hmrc/tai/model/domain/TaxedIncome.scala, app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala, app/uk/gov/hmrc/tai/model/domain/tracking/formatter/TrackedFormFormatters.scala, app/uk/gov/hmrc/tai/service/EmploymentService.scala, app/uk/gov/hmrc/tai/service/IncomeService.scala, app/uk/gov/hmrc/tai/service/TaxAccountService.scala, app/uk/gov/hmrc/tai/service/TaxAccountSummaryService.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceViewModel.scala, app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/EmploymentsConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/SessionConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala, test/uk/gov/hmrc/tai/model/domain/TaxCodeIncomeSpec.scala, test/uk/gov/hmrc/tai/model/domain/TaxComponentTypeSpec.scala, test/uk/gov/hmrc/tai/model/domain/income/NonTaxCodeIncomeComponentTypeSpec.scala, test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala, test/uk/gov/hmrc/tai/service/TaxAccountSummaryServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala, test/utils/TaxAccountSummaryTestData.scala
- [/] Unit tests passing
- [/] Coverage reached
- [/] Acceptance tests passing
=> [HMA-1095][PH] Re-introduce mobile work with updates

app/controllers/AuthProviderController.scala
=> Logging around auth entry points

app/controllers/AuthProviderController.scala, app/controllers/IncomeSourceSummaryController.scala, app/controllers/TaxAccountSummaryController.scala, app/controllers/WhatDoYouWantToDoController.scala, app/controllers/auth/AuthAction.scala, app/views/IncomeSourceSummary.scala.html, app/views/incomeTaxSummary.scala.html, app/views/whatDoYouWantToDoTileView.scala.html, test/controllers/IncomeSourceSummaryControllerSpec.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala, test/utils/TaxAccountSummaryTestData.scala
=> Applied auth-client to all controllers

app/uk/gov/hmrc/tai/config/wiring.scala
=> Get-help-fix: Fixed wsProxyServer for get-help page

conf/application.conf
=> DDCNOS-5463: re-added tai welsh toggle

app/controllers/i18n/TaiLanguageController.scala, conf/application.conf, project/FrontendBuild.scala, test/controllers/i18n/TaiLanguageControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxCodeDescriptorSpec.scala
=> Revert "DDCNOS-5463:updated play-language and language controller"

app/uk/gov/hmrc/tai/model/domain/AnnualAccount.scala, app/uk/gov/hmrc/tai/viewModels/PreviousYearUnderpaymentViewModel.scala, test/uk/gov/hmrc/tai/model/domain/AnnualAccountSpec.scala
=> DDCNOS-5608: Empty.max fix for Previous Year Underpayment issue

app/uk/gov/hmrc/tai/model/domain/AnnualAccount.scala, app/uk/gov/hmrc/tai/viewModels/PreviousYearUnderpaymentViewModel.scala, test/uk/gov/hmrc/tai/model/domain/AnnualAccountSpec.scala
=> Revert "DDCNOS-5608: Empty.max fix for Previous Year Underpayment issue"

app/uk/gov/hmrc/tai/model/domain/AnnualAccount.scala, app/uk/gov/hmrc/tai/viewModels/PreviousYearUnderpaymentViewModel.scala, test/uk/gov/hmrc/tai/model/domain/AnnualAccountSpec.scala
=> Revert "Revert "DDCNOS-5608: Empty.max fix for Previous Year Underpayment issue""

app/uk/gov/hmrc/tai/viewModels/TaxSummaryLabel.scala, test/uk/gov/hmrc/tai/viewModels/TaxSummaryLabelSpec.scala
=> added extra decimal places to estimated underpayment sentance

app/views/main.scala.html
=> UR banner text change

app/views/main.scala.html
=> ST-618 Added client id and corrected sessions for GTM

conf/messages, conf/messages.cy
- [yes] Unit tests passing
- [yes] Coverage reached
=> DDCNLS-6117-content changes

app/views/incomeTaxSummary.scala.html, app/views/main.scala.html, app/views/taxCodeChange/taxCodeComparison.scala.html, app/views/taxCodeChange/yourTaxFreeAmount.scala.html, app/views/taxCodeDetails.scala.html
=> Webchat optimizely off

app/views/main.scala.html
=> Testing chat shut down

app/views/main.scala.html
=> Revert "Testing chat shut down"

app/controllers/i18n/TaiLanguageController.scala, test/controllers/i18n/TaiLanguageControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxCodeDescriptorSpec.scala
=> Ddcnls 5913 Remove unnecessary validation stopping Welsh Lang working on Tech Diff page

app/controllers/pensions/AddPensionProviderController.scala, app/controllers/pensions/UpdatePensionProviderController.scala, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/controllers/pensions/UpdatePensionProviderControllerSpec.scala
=> Ddcnos 5733

app/controllers/YourIncomeCalculationController.scala, app/uk/gov/hmrc/tai/model/domain/Payment.scala, app/uk/gov/hmrc/tai/service/PaymentsService.scala, app/uk/gov/hmrc/tai/viewModels/PaymentDetailsViewModel.scala, app/uk/gov/hmrc/tai/viewModels/YourIncomeCalculationViewModel.scala, test/controllers/YourIncomeCalculationControllerSpec.scala, test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala, test/uk/gov/hmrc/tai/service/PaymentsServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/YourIncomeCalculationViewModelSpec.scala
=> Filter out duplicate payslips from income details

app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/controllers/employments/UpdateEmploymentController.scala, app/controllers/pensions/UpdatePensionProviderController.scala, app/uk/gov/hmrc/tai/forms/constaints/TelephoneNumberConstraint.scala, test/uk/gov/hmrc/tai/forms/constraints/TelephoneNumberConstraintSpec.scala
=> Ddcnls 4927

app/controllers/benefits/RemoveCompanyBenefitController.scala, app/uk/gov/hmrc/tai/model/domain/benefits/Benefits.scala, app/uk/gov/hmrc/tai/service/journeyCompletion/JourneyCompletionService.scala, project/Microservice.scala, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/BenefitsConnectorSpec.scala, test/uk/gov/hmrc/tai/service/benefits/BenefitsServiceSpec.scala
=> Ddcnls 6534

app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/service/journeyCompletion/JourneyCompletionService.scala, project/FrontendBuild.scala, test/controllers/auth/AuthActionSpec.scala
=> implemented new auth delegation

conf/messages.cy
=> DDCNLS-6583-Updated the welsh 

app/controllers/YourIncomeCalculationController.scala, app/views/incomes/historicIncomeCalculation.scala.html, app/views/incomes/yourIncomeCalculation.scala.html, app/views/print/historicIncomeCalculation.scala.html, app/views/print/yourIncomeCalculation.scala.html, test/controllers/YourIncomeCalculationControllerSpec.scala, test/views/html/incomes/HistoricIncomeCalculationSpec.scala, test/views/html/incomes/yourIncomeCalculationSpec.scala, test/views/html/print/HistoricIncomeCalculationSpec.scala, test/views/html/print/yourIncomeCalculationSpec.scala
=> DDCNOS-4268 | returning 502 when RTI is unavailable

app/controllers/PayeControllerHistoric.scala, test/controllers/PayeControllerHistoricSpec.scala
=> DDCNOS-4271 | Showing ServiceUnavailable page when RTI is down

app/controllers/PayeControllerHistoric.scala, test/controllers/PayeControllerHistoricSpec.scala
=> DDCNOS-4271 | putting check for empty list

app/controllers/ErrorPagesHandler.scala, app/controllers/YourIncomeCalculationController.scala, app/controllers/benefits/CompanyBenefitController.scala, test/views/html/incomes/yourIncomeCalculationSpec.scala
=> Ddcnos 5949

app/controllers/ExternalServiceRedirectController.scala, app/controllers/YourIncomeCalculationController.scala, app/controllers/benefits/CompanyBenefitController.scala, conf/tai.routes, test/controllers/ExternalServiceRedirectControllerSpec.scala, test/controllers/benefits/CompanyBenefitControllerSpec.scala, test/views/html/incomes/yourIncomeCalculationSpec.scala
=> DDCNLS-6538 | Ensure cache persists when editing benefits

app/controllers/ErrorPagesHandler.scala, app/controllers/PayeControllerHistoric.scala, app/controllers/YourIncomeCalculationController.scala, app/uk/gov/hmrc/tai/service/EmploymentService.scala, test/controllers/PayeControllerHistoricSpec.scala, test/controllers/YourIncomeCalculationControllerSpec.scala
=> DDCNOS-5985: Updated service unavailable view for 502 RTI unavailable

app/views/main.scala.html
=> Added sign out link to all pages (even if you are not authed)

app/controllers/IncomeController.scala, app/controllers/TaxAccountSummaryController.scala
=> DDCNOS-5969 expose exception alongside 500 status

app/views/incomeTaxSummary_incomeSourceDetail.scala.html
- [ yes ] Unit tests passing
- [ yes ] Coverage reached
- [ yes ] Acceptance tests passing
- [ yes ] Reviewed
=> Extra margin/space fixed/removed on tai home page

app/controllers/Webchat.scala, app/views/webchatPoc.scala.html, conf/tai.routes
=> A blank page for webchat

app/assets/sass/tai19032019.scss, app/views/IncomeSourceSummary.scala.html
- [ yes ] Unit tests passing
- [ yes ] Coverage reached
- [ yes ] Acceptance tests passing
- [ yes ] Reviewed
=> css updated to reduce heading margin

app/views/main.scala.html
=> Use TAAS for Nuance tag

project/FrontendBuild.scala
=> DEP-22: Changed version of TaaS to pull in nuance tag

app/views/main.scala.html
=> Revert "Use TAAS for Nuance tag"

project/FrontendBuild.scala
=> Revert "DEP-22: Changed version of TaaS to pull in nuance tag"

app/controllers/IncomeController.scala, test/controllers/IncomeControllerSpec.scala
=> DDCNL-8: Flush the cache on successful submission

app/views/main.scala.html
=> removed GTM code as it's no longer used

app/controllers/auth/AuthAction.scala, app/views/main.scala.html, test/builders/UserBuilder.scala, test/controllers/FakeAuthAction.scala, test/controllers/auth/AuthActionSpec.scala
=> DDCNL-1265 | Reinstate Trusted Helpers banner on TES

app/views/incomeTaxComparison/IncomeTax.scala.html, test/views/html/incomeTaxComparison/IncomeTaxSpec.scala, test/views/html/incomeTaxComparison/MainSpec.scala
=> DDCNL-1361 Fix to display £ properly and tests updated

app/views/incomeTaxComparison/IncomeSummary.scala.html, test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
=> table heading fixed for welsh

test/controllers/income/estimatedPay/update/IncomeUpdateBonusControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateHowToUpdateControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayPeriodControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayslipAmountControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateWorkingHoursControllerSpec.scala
=> Fixed intermittent tests

test/controllers/income/estimatedPay/update/IncomeUpdateBonusControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateEstimatedPayControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayPeriodControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayslipAmountControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateWorkingHoursControllerSpec.scala
=> Ddcnl 1420

app/controllers/ErrorPagesHandler.scala, app/controllers/UnauthorisedController.scala, app/uk/gov/hmrc/tai/config/ApplicationGlobal.scala, app/views/error_template_noauth.scala.html, conf/messages, conf/messages.cy
=> DDCNL-217 | Revise Page not found

app/controllers/income/UpdateIncomeNextYearController.scala, app/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeService.scala, test/controllers/income/UpdateIncomeNextYearControllerSpec.scala, test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
=> DDCNL-1458

README.md
=> DDCNL-1458-Added a white space for new build to pick new config

README.md
=> Removed a white space to pick up the new config

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
=> DDCNL-1571 | Provide default value for urls missing in config

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
=> DDCNL-1571 | Refactor links to use base root

app/controllers/PayeControllerHistoric.scala, app/uk/gov/hmrc/tai/binders/TaxYearObjectBinder.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf, test/controllers/PayeControllerHistoricSpec.scala, test/uk/gov/hmrc/tai/binders/TaxYearObjectBinderSpec.scala
=> DDCNL-1526 | Add support for CY-5

app/controllers/UnauthorisedController.scala, app/controllers/actions/ValidatePerson.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/connectors/HttpHandler.scala, app/uk/gov/hmrc/tai/connectors/PersonConnector.scala, app/uk/gov/hmrc/tai/connectors/responses/TaiResponse.scala, app/uk/gov/hmrc/tai/service/PersonService.scala, app/views/error_template_noauth.scala.html, app/views/main.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/controllers/UnauthorisedControllerSpec.scala, test/controllers/YourIncomeCalculationControllerSpec.scala, test/controllers/actions/ValidatePersonSpec.scala, test/uk/gov/hmrc/tai/connectors/PersonConnectorSpec.scala, test/uk/gov/hmrc/tai/service/PersonServiceSpec.scala, test/uk/gov/hmrc/tai/service/TaxAccountSummaryServiceSpec.scala, test/views/html/ErrorTemplateNoAuthSpec.scala
=> DDCNL-1267 | Implement content for Unauthorised page

app/controllers/TaxAccountSummaryController.scala, app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/connectors/TrackingConnector.scala, app/uk/gov/hmrc/tai/service/TrackingService.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, app/views/whatDoYouWantToDoTileView.scala.html, test/controllers/TaxAccountSummaryControllerSpec.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/TrackingConnectorSpec.scala, test/uk/gov/hmrc/tai/service/TrackingServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModelSpec.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> DDCNL-1645

app/assets/sass/tai19032019.scss, app/views/taxCodeChange/taxCodeComparison.scala.html
=> DDCNL-705 | Make Tax code titles clearer

app/views/print/printWrapper.scala.html, test/views/html/print/HistoricIncomeCalculationSpec.scala
=> Ddcnl 1559

app/controllers/TaxAccountSummaryController.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/model/domain/AnnualAccount.scala, app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncomeSourceStatus.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala, test/uk/gov/hmrc/tai/model/domain/AnnualAccountSpec.scala
=> DDCNL-1825

app/controllers/auth/AuthAction.scala, test/controllers/TaxAccountSummaryControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala
=> DDCNL-2408: Fixed users with no NINO not being uplifted properly

app/controllers/AuthProviderController.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/util/constants/TaiConstants.scala, test/builders/RequestBuilder.scala, test/controllers/auth/AuthActionSpec.scala, test/controllers/employments/EndEmploymentControllerSpec.scala
=> DDCNL-2551: Removed deprecated keys from SesisonKeys

app/controllers/PayeControllerHistoric.scala, app/uk/gov/hmrc/tai/service/EmploymentService.scala, app/views/paye/RtiDisabledHistoricPayAsYouEarn.scala.html, conf/messages, conf/messages.cy, test/controllers/PayeControllerHistoricSpec.scala, test/views/html/paye/RtiDownHistoricPayAsYouEarnSpec.scala
=> DDCNL-2428: New page for when RTI is disabled in historic paye

app/controllers/IncomeSourceSummaryController.scala, app/uk/gov/hmrc/tai/connectors/EmploymentsConnector.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceSummaryViewModel.scala, app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, app/uk/gov/hmrc/tai/viewModels/YourIncomeCalculationViewModel.scala, app/views/IncomeSourceSummary.scala.html, app/views/incomeTaxSummary.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/tai/connectors/EmploymentsConnectorSpec.scala, test/uk/gov/hmrc/tai/viewModels/IncomeSourceSummaryViewModelSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala, test/uk/gov/hmrc/tai/viewModels/YourIncomeCalculationViewModelSpec.scala, test/views/html/IncomeSourceSummaryViewSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala, test/views/html/incomes/yourIncomeCalculationSpec.scala, test/views/html/print/yourIncomeCalculationSpec.scala
=> DDCNL-2427

app/views/main.scala.html
=> DDCNL-2707: Define a user as SA if they have a UTR

README.md
=> Force a rebuild for app-config-base

app/controllers/TaxFreeAmountController.scala, app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala, app/uk/gov/hmrc/tai/service/CodingComponentService.scala, conf/application.conf, test/controllers/TaxFreeAmountControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala, test/uk/gov/hmrc/tai/service/CodingComponentServiceSpec.scala, test/uk/gov/hmrc/tai/service/UpdateNextYearsIncomeServiceSpec.scala
=> DDCNL-2466

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/main.scala.html, conf/application.conf
=> DDCNL-2746 | accessibility statement changes

app/uk/gov/hmrc/tai/util/constants/TaiConstants.scala, app/views/main.scala.html
=> DDCNL-2688 | Remove use of deprecated SessionKeys attributes

README.md
=> Updated the read me

README.md, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/config/wiring.scala, app/uk/gov/hmrc/tai/service/HasFormPartialService.scala, app/uk/gov/hmrc/tai/util/constants/TaiConstants.scala, app/views/main.scala.html, conf/application.conf, test/controllers/UnauthorisedControllerSpec.scala, test/uk/gov/hmrc/tai/model/IncomesSourcesSpec.scala
=> Ddcnl 2250

app/controllers/ServiceController.scala, app/controllers/UnauthorisedController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf, test/controllers/ServiceControllerSpec.scala, test/controllers/UnauthorisedControllerSpec.scala
=> DDCNL-3136: Migrate to bas gateway frontend

conf/application.conf
=> DDCNL-3616: IV uplift now gets sent to the real IV-FE

app/controllers/UnauthorisedController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, conf/application.conf, test/controllers/UnauthorisedControllerSpec.scala
=> DDCNL-3136: Use the correct continue param for sign in

conf/application.conf
=> DDCNL-3187: Use Lang HttpCookies only

app/views/main.scala.html, conf/application.conf, project/AppDependencies.scala
=> DDCNL-3119: tracking consent added

app/assets/sass/tai19032019.scss, app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, app/views/incomeTaxSummary.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/views/html/IncomeTaxSummaryViewSpec.scala
=> Ddcnl 3284

app/controllers/WhatDoYouWantToDoController.scala
=> Fix double call to JRS API

app/uk/gov/hmrc/tai/filters/TaxAccountFilter.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceComparisonViewModel.scala, app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/Main.scala.html, test/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/IncomeSourceComparisonViewModelSpec.scala, test/views/html/incomeTaxComparison/IncomeSummarySpec.scala
=> DDCNL-3516

project/plugins.sbt
=> DDCNL-3847 | removing bintray

app/controllers/WhatDoYouWantToDoController.scala, conf/application.conf, test/controllers/WhatDoYouWantToDoControllerSpec.scala
=> Fixed flakey test

app/controllers/IncomeController.scala, test/controllers/IncomeControllerSpec.scala
=> Fix race condition where caching was not completing before being accessed again on the redirected page

conf/application.conf
=> DDCNL-4116

app/assets/stylesheets/base/_table.scss, app/views/estimatedIncomeTax/DetailedIncomeTaxEstimateView.scala.html, app/views/includes/details_summary.scala.html
=> Ddcnl 4433

app/uk/gov/hmrc/tai/connectors/JrsConnector.scala, it/controllers/PotentialUnderpaymentControllerErrorHandlingSpec.scala, it/utils/MockTemplateRenderer.scala
=> DDCNL-5161: fixed it:tests, improved logging in JrsConnector

test/controllers/ErrorPagesHandlerSpec.scala, test/controllers/JrsClaimsControllerSpec.scala
=> Removing commented code

app/controllers/YourTaxCodeController.scala
=> Revert "DDCNL-5264: Adding logging to highlight a bug"

app/controllers/IncomeController.scala, test/controllers/IncomeControllerSpec.scala
=> PAYE-69 - handled exception for incorrect date format

app/controllers/WhatDoYouWantToDoController.scala
=> Payee 139 refactor what do you want to do controller

conf/messages, conf/messages.cy
=> Adding message key back in

app/controllers/ErrorPagesHandler.scala, app/controllers/auth/AuthAction.scala
=> PAYEE-200 - changing deprecated code

app/controllers/benefits/RemoveCompanyBenefitController.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/MainTempleteNew.scala.html, app/views/help/Link.scala.html, build.sbt, conf/application.conf, conf/messages, conf/messages.cy, conf/tai.routes, project/AppDependencies.scala
=> PAYEE-210 - Compiling - Added in new library, main template and helpers

app/uk/gov/hmrc/tai/model/TaxYear.scala
Signed-off-by: vivekhmrc <vivek.kumar@digital.hmrc.gov.uk>
=> PAYEE-246: Include the ZoneId for the LocalDate now

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/connectors/TrackingConnector.scala, app/uk/gov/hmrc/tai/util/Timeout.scala, conf/application.conf, test/uk/gov/hmrc/tai/connectors/TrackingConnectorSpec.scala, test/uk/gov/hmrc/tai/util/TimeoutSpec.scala
=> PAYEE-107 toggle tracking

app/assets/stylesheets/modules/_typography.scss, app/assets/stylesheets/tai.scss, app/views/IncomeTaxSummaryView.scala.html, app/views/MainTempleteNew.scala.html, app/views/includes/link.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomeTaxSummary_incomeSourceDetail.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala
=> PAYEE-197 - add new GDS classes and styles to CY page

app/assets/stylesheets/modules/_print.scss, app/views/MainTempleteNew.scala.html
=> PAYEE-197 fix check for BTA link and print style

app/assets/stylesheets/modules/_print.scss, app/views/MainTempleteNew.scala.html, app/views/includes/previousYearsSideNav.scala.html, app/views/includes/ptaHeader.scala.html, app/views/paye/HistoricPayAsYouEarnView.scala.html, test/views/html/paye/HistoricPayAsYouEarnViewSpec.scala
=> Payee 196 fe library upgrade check previous tax years

app/assets/stylesheets/modules/_cy-plus-one-income-tax-comparison.scss, app/assets/stylesheets/modules/_print.scss, app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/IncomeTax.scala.html, app/views/incomeTaxComparison/MainView.scala.html, app/views/incomeTaxComparison/TaxCodes.scala.html, app/views/incomeTaxComparison/TaxFreeAmount.scala.html, test/views/html/incomeTaxComparison/MainViewSpec.scala
=> PAYE-198: Upgrades check next tax year to use MainTempleteNew and the new GDS standard

app/controllers/IncomeController.scala, app/views/incomes/EditIncomeView.scala.html, conf/tai.routes, test/controllers/IncomeControllerSpec.scala
=> Payee 212 cache issues after updating estimated income

app/assets/stylesheets/tai.scss, app/views/MainTempleteNew.scala.html, app/views/TaxCodeDetailsPreviousYearsView.scala.html
Signed-off-by: vivekhmrc <vivek.kumar@digital.hmrc.gov.uk>
=> PAYEE-262: Upgrade the FE Library for Check previous tax years

app/assets/stylesheets/modules/_print.scss, app/views/JrsClaimSummaryView.scala.html
=> Payee 202 fe library upgrade coronavirus job retention scheme

app/assets/stylesheets/modules/_print.scss, app/views/incomes/HistoricIncomeCalculationView.scala.html, test/controllers/YourIncomeCalculationControllerSpec.scala, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomes/HistoricIncomeCalculationViewSpec.scala
* Upgrades HistoricIncomeCalculation view to new GDS
=> PAYEE-263:  Check previous tax years

app/assets/stylesheets/modules/_print.scss, app/assets/stylesheets/modules/_responsive_table.scss, app/views/IncomeSourceSummaryView.scala.html, app/views/MainTempleteNew.scala.html, test/views/html/IncomeSourceSummaryViewSpec.scala
=> Payee 293 cy pension details

app/views/PotentialUnderpaymentView.scala.html, test/views/html/PotentialUnderpaymentViewSpec.scala
=> PAYEE-305: Upgraded to new gds library

app/views/PotentialUnderpaymentView.scala.html, test/views/html/PotentialUnderpaymentViewSpec.scala
=> Payee 308 fe library upgrade check current tax year previous underpayment

app/views/MainTemplate.scala.html, app/views/WhatDoYouWantToDoTileView.scala.html, conf/application.conf, conf/messages, conf/messages.cy
=> PAYEE-213 - Implemented UR banner

app/assets/stylesheets/tai.scss, app/views/TaxCodeDetailsView.scala.html, test/views/html/TaxCodeDetailsViewSpec.scala
=> PAYEE-312: Upgrades tax-code-overview

README.md, app/controllers/AuthProviderController.scala, app/controllers/ServiceController.scala, app/controllers/UnauthorisedController.scala, app/controllers/auth/AuthAction.scala, app/uk/gov/hmrc/tai/model/UserDetails.scala, app/uk/gov/hmrc/tai/util/constants/TaiConstants.scala, app/views/MainTemplate.scala.html, app/views/main_without_nav.scala.html, conf/tai.routes, test/controllers/AuthProviderControllerSpec.scala, test/controllers/FakeAuthAction.scala, test/controllers/JrsClaimsControllerSpec.scala, test/controllers/ServiceControllerSpec.scala, test/controllers/UnauthorisedControllerSpec.scala, test/controllers/auth/AuthActionSpec.scala, test/uk/gov/hmrc/tai/model/UserDetailsSpec.scala, test/uk/gov/hmrc/tai/service/AuditServiceSpec.scala
=> PAYEE-342 - Removed verify from the service

test/views/html/estimatedIncomeTax/ComplexEstimatedIncomeTaxViewSpec.scala
Signed-off-by: vivekhmrc <vivek.kumar@digital.hmrc.gov.uk>
=> PAYEE-307: Review comments incorporated

app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, test/views/html/employments/UpdateRemoveEmploymentDecisionViewSpec.scala
=> PAYEE-314: updates UpdateRemoveEmploymentDecisionView.scala.html

app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, test/controllers/employments/EndEmploymentControllerSpec.scala, test/views/html/employments/UpdateRemoveEmploymentDecisionViewSpec.scala
=> Payee 314 fix title

app/views/estimatedIncomeTax/SimpleEstimatedIncomeTaxView.scala.html, app/views/estimatedIncomeTax/taxBandTable.scala.html, test/views/html/estimatedIncomeTax/SimpleEstimatedIncomeTaxViewSpec.scala, test/views/html/estimatedIncomeTax/taxBandTableSpec.scala
=> PAYEE-351: Upgraded view to new frontend library

app/views/incomes/YourIncomeCalculationView.scala.html
=> PAYEE-321: Upgraded view to new frontend library

app/views/IncomeSourceSummaryView.scala.html, app/views/IncomeTaxSummaryView.scala.html, app/views/JrsClaimSummaryView.scala.html, app/views/MainTempleteNew.scala.html, app/views/PotentialUnderpaymentView.scala.html, app/views/PreviousYearUnderpaymentView.scala.html, app/views/TaxCodeDetailsPreviousYearsView.scala.html, app/views/TaxCodeDetailsView.scala.html, app/views/employments/AddEmploymentNameFormView.scala.html, app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, app/views/estimatedIncomeTax/ComplexEstimatedIncomeTaxView.scala.html, app/views/estimatedIncomeTax/SimpleEstimatedIncomeTaxView.scala.html, app/views/incomeTaxComparison/MainView.scala.html, app/views/incomes/HistoricIncomeCalculationView.scala.html, app/views/paye/HistoricPayAsYouEarnView.scala.html, app/views/taxCodeChange/TaxCodeComparisonView.scala.html
=> PAYEE-425 - Added toggle for back link

app/views/estimatedIncomeTax/ZeroTaxEstimatedIncomeTaxView.scala.html, app/views/incomes/YourIncomeCalculationView.scala.html
=> PAYEE-425 - Fixed tests

app/views/employments/AddEmploymentPayrollNumberFormView.scala.html, project/AppDependencies.scala, test/controllers/employments/AddEmploymentControllerSpec.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/employments/AddEmploymentPayrollNumberFormViewSpec.scala
=> Payee 359 employer journey 002

app/views/employments/AddEmploymentPayrollNumberFormView.scala.html
=> Fixed tests

app/views/employments/ConfirmationView.scala.html, app/views/includes/confirmationSuccessBanner.scala.html, app/views/includes/confirmation_summary.scala.html
=> Payee 362 add a missing employer journey 005

app/uk/gov/hmrc/tai/forms/employments/EmploymentAddDateForm.scala, app/views/employments/AddEmploymentStartDateFormView.scala.html, project/AppDependencies.scala, test/controllers/employments/AddEmploymentControllerSpec.scala, test/views/html/employments/AddEmploymentStartDateFormViewSpec.scala
=> PAYEE-358 - upgrade FE and add twirl date component

app/views/employments/AddEmploymentNameFormView.scala.html
=> removes form content

app/uk/gov/hmrc/tai/forms/employments/EmploymentEndDateForm.scala, app/views/employments/AddEmploymentPayrollNumberFormView.scala.html, app/views/employments/EndEmploymentView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/employments/EndEmploymentViewSpec.scala
=> PAYEE-365 add govukDateInput component , gds styles,  fix tests

app/views/estimatedIncomeTax/ZeroTaxEstimatedIncomeTaxView.scala.html, app/views/includes/cancelLink.scala.html, app/views/includes/checkYourAnswers.scala.html, app/views/includes/forms/submit.scala.html, app/views/incomes/AddIncomeCheckYourAnswersView.scala.html, app/views/incomes/YourIncomeCalculationView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/benefits/RemoveCompanyBenefitCheckYourAnswersViewSpec.scala, test/views/html/employments/update/UpdateEmploymentCheckYourAnswersViewSpec.scala, test/views/html/incomes/AddIncomeCheckYourAnswersViewSpec.scala, test/views/html/incomes/estimatedPayment/update/CheckYourAnswersViewSpec.scala, test/views/html/incomes/previousYears/CheckYourAnswersViewSpec.scala, test/views/html/pensions/AddPensionCheckYourAnswersViewSpec.scala, test/views/html/pensions/updatePensions/UpdatePensionsCheckYourAnswersViewSpec.scala
=> Payee 361 add a missing employer journey 004

app/assets/stylesheets/modules/_cya-tax-summary.scss, app/views/TaxFreeAmountView.scala.html, app/views/includes/taxFreeAmountSummary.scala.html, test/views/html/TaxFreeAmountViewSpec.scala
=> Payee 306 fe upgrade cy tax free amount

app/views/includes/taxFreeAmountSummaryComparison.scala.html, app/views/taxCodeChange/YourTaxFreeAmountView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/views/html/taxCodeChange/YourTaxFreeAmountViewSpec.scala
=> PAYEE-416 update FE classes and fix tests

app/views/taxCodeChange/WhatHappensNextView.scala.html, test/views/html/taxCodeChange/WhatHappensNextViewSpec.scala
=> PAYEE-417 FE update tax code change what happens next

app/views/includes/iFormInProgressBanner.scala.html, conf/messages, conf/messages.cy
=> PAYEE-336: Fix the Notification Banner

app/uk/gov/hmrc/tai/viewModels/HistoricPayAsYouEarnViewModel.scala, app/views/paye/HistoricPayAsYouEarnView.scala.html, test/views/html/paye/HistoricPayAsYouEarnViewSpec.scala, test/views/html/paye/RtiDownHistoricPayAsYouEarnViewSpec.scala
=> Payee 432 Employer PAYE reference (ERN) on previous tax years summary page

app/views/employments/update/UpdateEmploymentCheckYourAnswersView.scala.html, test/views/html/employments/update/UpdateEmploymentCheckYourAnswersViewSpec.scala
=> PAYEE-367: updates UpdateEmploymentCheckYourAnswersView

app/views/incomeTaxSummary_incomeSourceDetail.scala.html, conf/messages, conf/messages.cy
=> PAYEE-455 - Changed payroll number to pension number for pensions

app/controllers/income/estimatedPay/update/IncomeUpdateHowToUpdateController.scala, app/views/incomes/HowToUpdateView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomes/HowToUpdateViewSpec.scala
=> PAYEE-378: FE update: HowToUpdateView

app/views/incomes/EstimatedPayLandingPageView.scala.html, test/views/html/incomes/EstimatedPayLandingPageViewSpec.scala
=> PAYEE-377 Update taxable income 001

app/views/incomes/PayPeriodView.scala.html, test/views/html/incomes/PayPeriodViewSpec.scala
=> PAYEE-381 - update how often you get paid view

app/controllers/IncomeTaxHistoryController.scala, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, conf/messages, conf/messages.cy, test/controllers/IncomeTaxHistoryControllerSpec.scala, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
=> PAYEE-466 - display unavailable if tax code couldn't be retrieved

app/assets/stylesheets/modules/_print.scss, app/views/includes/printBanner.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
=> PAYEE-438 add print formatting

app/views/includes/compareValueInput.scala.html, app/views/includes/compareValueInputNew.scala.html, app/views/incomes/EditIncomeView.scala.html, test/views/html/incomes/EditIncomeViewSpec.scala
=> Payee 380 - FE upgrade - income-journey-004

app/views/incomes/EstimatedPayView.scala.html, test/views/html/incomes/EstimatedPayViewSpec.scala
=> PAYEE-389: Page upgraded to new fe library

app/views/incomes/PayslipAmountView.scala.html, test/views/html/incomes/PayslipAmountViewSpec.scala
=> PAYEE-383 - update enter payslip amount

app/views/includes/compareValueInputNew.scala.html, app/views/includes/editIncomeWhatShouldYouInclude.scala.html, app/views/incomes/EditIncomeIrregularHoursView.scala.html, app/views/incomes/EditIncomeView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomes/EditIncomeIrregularHoursViewSpec.scala
=> PAYEE-382 - update edit income irregular hours

app/controllers/IncomeTaxHistoryController.scala
=> PAYEE-history-view-add-tax-district: adds taxDistrictNumber to the ERN

app/controllers/IncomeTaxHistoryController.scala, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html
=> Fixed date format issue fr income tax history

app/assets/stylesheets/modules/_income_tax_history.scss, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html
=> PAYEE-508 format updates

app/views/incomes/WorkingHoursView.scala.html, test/views/html/incomes/WorkingHoursViewSpec.scala
=> Payee 379 working hours

app/views/incomes/BonusPaymentAmountView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomes/BonusPaymentAmountViewSpec.scala
=> PAYEE-387 upgrade fe  estimated taxable income journey - 011

app/views/benefits/RemoveCompanyBenefitStopDateView.scala.html, test/views/html/benefits/RemoveCompanyBenefitStopDateViewSpec.scala
=> PAYEE-420: update remove company benefits stop date view

app/views/benefits/UpdateOrRemoveCompanyBenefitDecisionView.scala.html, test/views/html/benefits/UpdateOrRemoveCompanyBenefitDecisionViewSpec.scala
=> PAYEE-419: update update or remove company benefit decision view

app/views/CanWeContactByPhoneView.scala.html, app/views/benefits/RemoveBenefitTotalValueView.scala.html, test/views/html/benefits/RemoveBenefitTotalValueViewSpec.scala
=> PAYEE-422: update remove benefit total value

app/views/pensions/AddPensionErrorView.scala.html, test/views/html/pensions/AddPensionErrorViewSpec.scala
=> PAYEE-394 - update FE lib

app/controllers/pensions/AddPensionProviderController.scala, app/views/CanWeContactByPhoneViewWithBackLink.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala
=> PAYEE-522: temporary fix for pension

app/views/incomes/ConfirmAmountEnteredView.scala.html, test/views/html/incomes/ConfirmAmountEnteredViewSpec.scala
=> PAYEE-390: update confirm amount entered

app/controllers/IncomeTaxHistoryController.scala, app/uk/gov/hmrc/tai/viewModels/incomeTaxHistory/IncomeTaxHistoryViewModel.scala, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, conf/messages, conf/messages.cy, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
… current date show not applicable
=> PAYEE-501: Instead of showing current date show not applicable when end date is not present

app/views/benefits/RemoveCompanyBenefitCheckYourAnswersView.scala.html, test/views/html/benefits/RemoveCompanyBenefitCheckYourAnswersViewSpec.scala
=> PAYEE-423: Upgraded to new FE library

app/views/pensions/AddPensionReceivedFirstPayView.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/views/html/pensions/AddPensionReceivedFirstPayViewSpec.scala
=> PAYEE-393: update pension received first pay view

app/views/pensions/AddPensionNameView.scala.html, test/views/html/pensions/AddPensionNameViewSpec.scala
=> PAYEE-392: update add pension name

app/views/pensions/AddPensionNumberView.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/views/html/pensions/AddPensionNumberViewSpec.scala
=> PAYEE-396 upgrade FE

app/uk/gov/hmrc/tai/forms/pensions/PensionAddDateForm.scala, app/views/pensions/AddPensionStartDateView.scala.html, test/views/html/pensions/AddPensionStartDateViewSpec.scala
=> PAYEE-395: update add pension start date view

app/views/includes/checkYourAnswers.scala.html, app/views/pensions/AddPensionCheckYourAnswersView.scala.html, test/views/html/pensions/AddPensionCheckYourAnswersViewSpec.scala
=> PAYEE-398: Add Pension Provider: Check your answers HMRC library upgrade

app/views/pensions/AddPensionConfirmationView.scala.html
=> PAYEE-399: update add pension confirmation view

app/views/pensions/update/ConfirmationView.scala.html
=> PAYEE-404: update ConfirmationView.scala.html

app/views/pensions/update/UpdatePensionCheckYourAnswersView.scala.html, test/views/html/pensions/updatePensions/UpdatePensionsCheckYourAnswersViewSpec.scala
=> PAYEE-403: updates UpdatePensionCheckYourAnswersView

app/views/pensions/update/WhatDoYouWantToTellUsView.scala.html, test/views/html/pensions/updatePensions/WhatDoYouWantToTellUsViewSpec.scala
=> PAYEE-401: update what do you want to tell us view

app/views/incomes/EditPensionView.scala.html, test/views/html/incomes/EditPensionViewSpec.scala
=> PAYEE-408: updates EditPensionView.scala.html

app/views/pensions/update/DoYouGetThisPensionIncomeView.scala.html, test/views/html/pensions/DoYouGetThisPensionIncomeViewSpec.scala
=> Payee 400 update pension provider 001

app/uk/gov/hmrc/tai/viewModels/income/estimatedPay/update/DuplicateSubmissionEmploymentViewModel.scala, app/views/incomes/DuplicateSubmissionWarningView.scala.html, test/views/html/incomes/DuplicateSubmissionWarningViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1WarningViewSpec.scala
=> PAYEE-406 upgrade FE

app/views/includes/cancelLink.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1EditView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1TemplateNew.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1EditViewSpec.scala
* updates UpdateIncomeCYPlus1EditView.scala.html
* adds temporary UpdateIncomeCYPlus1TemplateNew.scala.html
* adds form error to ptaHeader.scala.html
=> PAYEE-412:

app/views/includes/cancelLink.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1EditView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1StartView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1TemplateNew.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1EditViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1StartViewSpec.scala
=> Payee 411: updates UpdateIncomeCYPlus1StartView.scala.html

app/views/incomes/nextYear/UpdateIncomeCYPlus1SuccessView.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1SuccessViewSpec.scala
=> Payee 414 estimated income journey 004

app/assets/stylesheets/tai.scss, app/views/incomes/EditPensionSuccessView.scala.html
=> PAYEE-410  - update FE 

app/views/incomes/nextYear/UpdateIncomeCYPlus1WarningView.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1WarningViewSpec.scala
=> Payee-547: update income cyplus1 warning

app/views/incomes/previousYears/UpdateIncomeDetailsDecisionView.scala.html, test/views/html/incomes/previousYears/UpdateIncomeDetailsDecisionViewSpec.scala
=> PAYEE-426: update UpdateIncomeDetailsDecisionView.scala.html

app/views/employments/EndEmploymentView.scala.html, app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, app/views/employments/update/UpdateEmploymentCheckYourAnswersView.scala.html, app/views/employments/update/WhatDoYouWantToTellUsView.scala.html, app/views/incomes/AddIncomeCheckYourAnswersView.scala.html
=> PAYEE-538 - Added backLinkUrl to page 002

app/controllers/pensions/AddPensionProviderController.scala, app/views/pensions/AddPensionCheckYourAnswersView.scala.html, app/views/pensions/AddPensionErrorView.scala.html, app/views/pensions/AddPensionNameView.scala.html, app/views/pensions/AddPensionNumberView.scala.html, app/views/pensions/AddPensionReceivedFirstPayView.scala.html, app/views/pensions/AddPensionStartDateView.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/views/html/pensions/AddPensionNameViewSpec.scala, test/views/html/pensions/AddPensionReceivedFirstPayViewSpec.scala, test/views/html/pensions/AddPensionStartDateViewSpec.scala
=> PAYEE-535: fix backLink for Add missing Pension Journey

app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala, test/uk/gov/hmrc/tai/model/domain/TaxCodeRecordSpec.scala
without affecting the existing behaviour
=> PAYEE-556: Incorporate DES changes to replace Week1/Month1 by Week 1 Month 1

app/controllers/pensions/UpdatePensionProviderController.scala, app/views/pensions/update/DoYouGetThisPensionIncomeView.scala.html, app/views/pensions/update/UpdatePensionCheckYourAnswersView.scala.html, app/views/pensions/update/WhatDoYouWantToTellUsView.scala.html, test/views/html/pensions/updatePensions/UpdatePensionsCheckYourAnswersViewSpec.scala, test/views/html/pensions/updatePensions/WhatDoYouWantToTellUsViewSpec.scala
=> PAYEE-539: fix backLink for update or remove pension provider

app/views/incomes/SameEstimatedPayView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1SameView.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1SameViewSpec.scala
=> PAYEE-548: update SameEstimatedPayView and UpdateIncomeCYPlus1SameView

app/controllers/benefits/CompanyBenefitController.scala, app/controllers/benefits/RemoveCompanyBenefitController.scala, app/uk/gov/hmrc/tai/viewModels/benefit/CompanyBenefitDecisionViewModel.scala, app/views/benefits/RemoveCompanyBenefitCheckYourAnswersView.scala.html, app/views/benefits/RemoveCompanyBenefitStopDateView.scala.html, app/views/benefits/UpdateOrRemoveCompanyBenefitDecisionView.scala.html, test/controllers/benefits/CompanyBenefitControllerSpec.scala, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala, test/uk/gov/hmrc/tai/viewModels/benefit/CompanyBenefitDecisionViewModelSpec.scala, test/views/html/benefits/RemoveCompanyBenefitCheckYourAnswersViewSpec.scala, test/views/html/benefits/RemoveCompanyBenefitStopDateViewSpec.scala, test/views/html/benefits/UpdateOrRemoveCompanyBenefitDecisionViewSpec.scala
=> PAYEE-537: fix backLink update or remove company benefit

app/views/incomes/previousYears/CheckYourAnswersView.scala.html, test/views/html/incomes/previousYears/CheckYourAnswersViewSpec.scala
=> PAYEE-429 - Upgraded check your answers page

app/views/incomes/previousYears/UpdateIncomeDetailsConfirmationView.scala.html
=> PAYEE-430: update UpdateIncomeDetailsConfirmationView.scala.html

app/views/incomes/previousYears/UpdateIncomeDetailsView.scala.html, test/views/html/incomes/previousYears/UpdateIncomeDetailsViewSpec.scala
=> PAYEE-427: update UpdateIncomeDetailsView.scala.html

app/views/employments/DuplicateSubmissionWarningView.scala.html, app/views/includes/duplicateSubmissionWarning.scala.html, app/views/pensions/DuplicateSubmissionWarningView.scala.html, test/views/html/employments/DuplicateSubmissionWarningViewSpec.scala, test/views/html/pensions/updatePensions/DuplicateSubmissionWarningViewSpec.scala
=> PAYEE-557: update duplicateSubmissionWarning.scala.html

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/MainTempleteNew.scala.html
=> PAYEE-546 - Fixing broken feedback link

app/views/MainTempleteNew.scala.html, app/views/ManualCorrespondenceView.scala.html
=> FE updates and remove unused main template param

app/views/NoCYIncomeTaxErrorView.scala.html, test/views/html/NoCYIncomeTaxErrorViewSpec.scala
=> PAYEE-582 - Updated NoCYIncomeTaxErrorController page

app/views/TimeoutView.scala.html
=> PAYEE-588: update TimeoutView.scala.html

app/controllers/benefits/RemoveCompanyBenefitController.scala, app/views/MainTempleteNew.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/views/html/benefits/RemoveCompanyBenefitStopDateViewSpec.scala, test/views/html/incomeTaxComparison/MainViewSpec.scala, test/views/html/paye/HistoricPayAsYouEarnViewSpec.scala
=> PAYEE-540  Update MainTempleteNew to use backLinkId

app/views/ErrorNoPrimary.scala.html
=> PAYEE-584 - Upgraded ErrorNoPrimary

app/views/InternalServerErrorView.scala.html
=> PAYEE-586 - Updated InternalServerErrorView

app/views/MainTempleteNew.scala.html, conf/messages, conf/messages.cy
=> PAYEE-617: add Error to title page if the form has an error

app/views/help/GetHelpView.scala.html
=>  PAYEE-597: update GetHelpView.scala.html

app/views/DeceasedHelplineView.scala.html, test/views/html/DeceasedHelplineViewSpec.scala
=> PAYEE-583: update DeceasedHelplineView.scala.html

app/views/employments/AddEmploymentStartDateFormView.scala.html, conf/messages, conf/messages.cy, test/views/html/employments/AddEmploymentStartDateFormViewSpec.scala
=> update add employment page

app/views/ErrorTemplateNoauth.scala.html, test/controllers/ErrorPagesHandlerSpec.scala
=> PAYEE-585: Updated error template no auth + spec

app/views/estimatedIncomeTax/NoCurrentIncomeView.scala.html, test/views/html/estimatedIncomeTax/NoCurrentIncomeViewSpec.scala
=> PAYEE-596: update NoCurrentIncomeView.scala.html

app/views/paye/RtiDisabledHistoricPayAsYouEarnView.scala.html, test/views/html/paye/RtiDownHistoricPayAsYouEarnViewSpec.scala
=>  PAYEE-604:update RtiDisabledHistoricPayAsYouEarnView.scala.html

app/views/employments/EndEmploymentWithinSixWeeksErrorView.scala.html
=> FE library updates EndEmploymentWithinSixWeeksErrorView

app/views/IncomeTaxSummaryView.scala.html
=>  PAYEE-625:  changes back link to 'PAYE Income Tax overview'

app/views/includes/yourTaxGraph.scala.html
=> PAYEE-488: disable reader in empty cells

app/views/taxCodeChange/TaxCodeComparisonView.scala.html
=>  PAYEE-624:  changes back link to 'PAYE Income Tax overview'

app/views/paye/HistoricPayAsYouEarnView.scala.html, app/views/paye/RtiDisabledHistoricPayAsYouEarnView.scala.html
=> PAYEE-626: change backlink content to PAYE Income Tax overview

app/assets/javascripts/newcard.js, app/assets/stylesheets/modules/_card.scss, app/assets/stylesheets/tai.scss, app/views/MainTempleteNew.scala.html, app/views/WhatDoYouWantToDoTileView.scala.html, app/views/includes/forms/card.scala.html, project/AppDependencies.scala
=> PAYEE -589 FE Library Upgrade - WhatDoYouWantToDoTileView 

app/views/incomes/YourIncomeCalculationView.scala.html, conf/messages, conf/messages.cy, test/views/html/incomes/YourIncomeCalculationViewSpec.scala
=> PAYEE-574: Add employer's name to page above taxable income table

app/views/CanWeContactByPhoneView.scala.html, app/views/incomes/previousYears/UpdateIncomeDetailsDecisionView.scala.html, app/views/incomes/previousYears/UpdateIncomeDetailsView.scala.html
=> PAYEE-606:  Error handling - Send us an update journey

app/views/CanWeContactByPhoneView.scala.html, app/views/pensions/AddPensionErrorView.scala.html, app/views/pensions/AddPensionNameView.scala.html, app/views/pensions/AddPensionNumberView.scala.html, app/views/pensions/AddPensionReceivedFirstPayView.scala.html, app/views/pensions/AddPensionStartDateView.scala.html, app/views/pensions/DuplicateSubmissionWarningView.scala.html
=> PAYEE-609 - Usability fix - Adding error to the page itle

app/views/CanWeContactByPhoneView.scala.html, app/views/pensions/update/DoYouGetThisPensionIncomeView.scala.html, app/views/pensions/update/WhatDoYouWantToTellUsView.scala.html
=> PAYEE-611 update formErrorSummary 

app/views/employments/EndEmploymentView.scala.html, app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, app/views/employments/update/WhatDoYouWantToTellUsView.scala.html
=> PAYEE-613:  Error handling - Update or remove employer journey

app/views/incomes/nextYear/UpdateIncomeCYPlus1EditView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1Template.scala.html
=> PAYEE-615: Usability fix - Add error to title of UpdateEstimatedIncome

app/assets/images/printer-icon-hmrc-1.svg, app/assets/stylesheets/tai.scss, app/controllers/YourTaxCodeController.scala, app/uk/gov/hmrc/tai/viewModels/TaxCodeViewModelPreviousYears.scala, app/views/MainTempleteNew.scala.html, app/views/TaxCodeDetailsPreviousYearsView.scala.html, app/views/includes/printBanner.scala.html, app/views/includes/ptaHeader.scala.html, test/uk/gov/hmrc/tai/viewModels/TaxCodeViewModelPreviousYearsSpec.scala
=> added print button to view and to css

app/assets/images/printer-icon-hmrc-1.svg, app/assets/stylesheets/tai.scss, app/controllers/YourTaxCodeController.scala, app/views/IncomeSourceSummaryView.scala.html, app/views/MainTempleteNew.scala.html, app/views/TaxCodeDetailsPreviousYearsView.scala.html, app/views/includes/printBanner.scala.html, app/views/includes/ptaHeader.scala.html
=> Payee-300: Change print link for 'View and update employment details' page

app/assets/stylesheets/modules/_print.scss, app/views/TaxCodeDetailsPreviousYearsView.scala.html, app/views/WhatDoYouWantToDoTileView.scala.html
=> updated print layout

app/controllers/TaxFreeAmountController.scala, app/views/TaxFreeAmountView.scala.html, test/views/html/TaxFreeAmountViewSpec.scala
=> PAYEE-303 - Print functionality

app/assets/stylesheets/modules/_print.scss, app/controllers/TaxCodeChangeController.scala, app/uk/gov/hmrc/tai/viewModels/taxCodeChange/TaxCodeChangeViewModel.scala, app/views/includes/details_summary.scala.html, app/views/taxCodeChange/TaxCodeComparisonView.scala.html, test/controllers/TaxCodeChangeControllerSpec.scala, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/uk/gov/hmrc/tai/viewModels/taxCodeChange/TaxCodeChangeViewModelSpec.scala, test/views/html/estimatedIncomeTax/DetailedIncomeTaxEstimateViewSpec.scala, test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
=> PAYEE-296 add print feature , update viewModel and tests with username

app/views/incomeTaxComparison/MainView.scala.html, test/views/html/incomeTaxComparison/MainViewSpec.scala
=> PAYEE-581 - Changed print button to link

app/assets/stylesheets/modules/_print.scss, app/views/estimatedIncomeTax/ComplexEstimatedIncomeTaxView.scala.html, app/views/estimatedIncomeTax/SimpleEstimatedIncomeTaxView.scala.html, app/views/estimatedIncomeTax/ZeroTaxEstimatedIncomeTaxView.scala.html, app/views/includes/yourTaxGraph.scala.html, conf/messages, test/controllers/EstimatedIncomeTaxControllerSpec.scala
=> PAYEE-304 - Added print functionality for complex view

app/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModel.scala, test/uk/gov/hmrc/tai/viewModels/IncomeSourceViewModelSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxAccountSummaryViewModelSpec.scala, test/utils/TaxAccountSummaryTestData.scala
=> PAYEE-683: displays ceased employments after the current tax year

app/views/employments/AddEmploymentStartDateFormView.scala.html, app/views/employments/EndEmploymentView.scala.html, app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, app/views/employments/update/WhatDoYouWantToTellUsView.scala.html, app/views/includes/duplicateSubmissionWarning.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomes/BonusPaymentAmountView.scala.html, app/views/incomes/BonusPaymentsView.scala.html, app/views/incomes/HowToUpdateView.scala.html, app/views/incomes/PayPeriodView.scala.html, app/views/incomes/PayslipAmountView.scala.html, app/views/incomes/PayslipDeductionsView.scala.html, app/views/incomes/TaxablePayslipAmountView.scala.html, app/views/incomes/WorkingHoursView.scala.html
=> PAYEE-703 update css to fix  text flow issue for  long company name

app/controllers/income/estimatedPay/update/IncomeUpdatePayslipAmountController.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayslipAmountControllerSpec.scala
=> PAYEE-732 - Aggregating journey cache calls

app/views/IncomeSourceSummaryView.scala.html, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, app/views/incomes/EditIncomeIrregularHoursView.scala.html, app/views/incomes/EstimatedPayLandingPageView.scala.html, app/views/paye/HistoricPayAsYouEarnView.scala.html, app/views/pensions/AddPensionNumberView.scala.html, app/views/pensions/AddPensionReceivedFirstPayView.scala.html, app/views/pensions/AddPensionStartDateView.scala.html
=> PAYEE-749 fix overflow issues for long employment names

app/controllers/income/estimatedPay/update/IncomeUpdatePayPeriodController.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala, test/controllers/income/estimatedPay/update/IncomeUpdatePayPeriodControllerSpec.scala
=> PAYEE - Aggregating journey cache calls

app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, app/uk/gov/hmrc/tai/forms/benefits/CompanyBenefitTotalValueForm.scala, app/uk/gov/hmrc/tai/forms/benefits/DateForm.scala, app/uk/gov/hmrc/tai/forms/employments/AddEmploymentPayrollNumberForm.scala, app/uk/gov/hmrc/tai/forms/employments/EmploymentEndDateForm.scala, app/uk/gov/hmrc/tai/forms/employments/EmploymentNameForm.scala, app/uk/gov/hmrc/tai/forms/employments/UpdateRemoveEmploymentForm.scala, app/uk/gov/hmrc/tai/forms/formValidator/BaseValidator.scala, app/uk/gov/hmrc/tai/forms/pensions/AddPensionProviderNumberForm.scala, app/uk/gov/hmrc/tai/forms/pensions/PensionProviderNameForm.scala, app/uk/gov/hmrc/tai/forms/pensions/UpdateRemovePensionForm.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala, app/uk/gov/hmrc/tai/viewModels/IncomeSourceComparisonViewModel.scala, app/uk/gov/hmrc/tai/viewModels/incomeTaxComparison/EstimatedIncomeTaxComparisonViewModel.scala, app/views/includes/taxFreeAmountSummary.scala.html, app/views/incomes/HistoricIncomeCalculationView.scala.html, app/views/print/HistoricIncomePrintView.scala.html, test/uk/gov/hmrc/tai/model/domain/BankAccountSpec.scala
=> PAYEE-726: Refactor list manipulation to follow scala conventions

app/controllers/IncomeController.scala, app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, app/controllers/income/estimatedPay/update/IncomeUpdateEstimatedPayController.scala, app/controllers/income/estimatedPay/update/IncomeUpdateHowToUpdateController.scala, app/uk/gov/hmrc/tai/util/FutureOps.scala, app/views/incomes/HowToUpdateView.scala.html, conf/tai.routes, test/controllers/IncomeControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateEstimatedPayControllerSpec.scala, test/controllers/income/estimatedPay/update/IncomeUpdateHowToUpdateControllerSpec.scala, test/views/html/incomes/HowToUpdateViewSpec.scala
=> PAYEE-717 - Persisting empId in the URL to avoid cache exceptions

app/views/IncomeTaxSummaryView.scala.html, app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/IncomeTax.scala.html, app/views/incomeTaxComparison/TaxCodes.scala.html, app/views/incomeTaxComparison/TaxFreeAmount.scala.html, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html
=> PAYEE-799 fix invalid html and accessibility issues

app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala
=> PAYEE-736: Removes deprecated mandatoryValueAs

app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala
=> PAYEE-738: Removes deprecated mappedMandatoryDeprecated

app/uk/gov/hmrc/tai/model/TaxYear.scala, app/uk/gov/hmrc/tai/util/TaxYearRangeUtil.scala, app/uk/gov/hmrc/tai/util/constants/TaiConstants.scala
=> PAYEE-720 - Getting timezone from TaiContants

app/views/WhatDoYouWantToDoTileView.scala.html, app/views/incomes/YourIncomeCalculationView.scala.html
=> PAYEE-800-fix-heading-order accessibility issue

app/views/employments/AddEmploymentErrorPageView.scala.html, test/views/html/employments/AddEmploymentErrorPageViewSpec.scala
=> updated view to MainTemplate and fix test

app/controllers/UnauthorisedController.scala, app/controllers/benefits/RemoveCompanyBenefitController.scala, app/controllers/employments/AddEmploymentController.scala, app/controllers/employments/EndEmploymentController.scala, app/controllers/employments/UpdateEmploymentController.scala, app/controllers/income/previousYears/UpdateIncomeDetailsController.scala, app/controllers/pensions/AddPensionProviderController.scala
=> updated injected views in controllers to camel case

app/controllers/IncomeController.scala, app/controllers/testOnly/TaiUpdateIncomeController.scala, app/uk/gov/hmrc/tai/connectors/JourneyCacheConnector.scala, app/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheService.scala, app/uk/gov/hmrc/tai/util/constants/JourneyCacheConstants.scala, conf/tai.routes, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/IncomeControllerSpec.scala, test/controllers/testOnly/TaiUpdateIncomeControllerSpec.scala, test/uk/gov/hmrc/tai/service/journeyCache/JourneyCacheServiceSpec.scala
=> PAYEE-594: Facilitator to drop the cache for acceptance tests

app/controllers/IncomeTaxComparisonController.scala
=> PAYEE-832: Uses mapN rather than eager evaluation

app/controllers/PayeControllerHistoric.scala
=> PAYEE-834: Replace eager evaluation with mapN in PayeControllerHistoric

app/controllers/PotentialUnderpaymentController.scala
=> PAYEE-835: Replace eager evaluation with mapN in PotentialUnderpaymentController

app/views/WhatDoYouWantToDoTileView.scala.html, app/views/incomes/YourIncomeCalculationView.scala.html, test/views/html/incomes/YourIncomeCalculationViewSpec.scala
=> PAYEE-801 fix heading order issue

app/controllers/IncomeSourceSummaryController.scala
=> PAYEE-831 - Applying calls in parrallel

app/assets/stylesheets/modules/_card.scss
=> Payee 803 - fix mobile layout issue on Tile view

app/controllers/IncomeController.scala
=> PAYEE 830: Update IncomeController.confirmRegularIncome confirmPensionIncome call to be applied in parallel

app/controllers/IncomeSourceSummaryController.scala, app/controllers/income/estimatedPay/update/IncomeUpdatePayPeriodController.scala
=> updated payPeriodPage method to be parallel

app/assets/stylesheets/tai.scss, app/views/incomeTaxComparison/MainView.scala.html, test/views/html/incomeTaxComparison/MainViewSpec.scala
=> Payee 804 - update gds notification banner 

app/controllers/income/estimatedPay/update/IncomeUpdateBonusController.scala
=> PAYEE-837: Applying calls in parallel for IncomeUpdateBonusController

app/controllers/income/estimatedPay/update/IncomeUpdateWorkingHoursController.scala
=> PAYEE-841: Applying calls in parallel for IncomeUpdateWorkingHoursController

app/controllers/IncomeSourceSummaryController.scala, app/uk/gov/hmrc/tai/forms/DateForm.scala
=> PAYEE-842: Make calls be applied in parallel

app/controllers/IncomeSourceSummaryController.scala, app/controllers/income/estimatedPay/update/IncomeUpdateCalculatorController.scala, test/controllers/income/estimatedPay/update/IncomeUpdateCalculatorControllerSpec.scala
=> PAYEE-838: refactors handleCalculationResult and onPageLoad

app/controllers/ErrorPagesHandler.scala, app/controllers/PotentialUnderpaymentController.scala, app/views/incomes/YourIncomeCalculationView.scala.html
=> PAYEE-874 - Removed duplicate text

app/controllers/ExternalServiceRedirectController.scala, app/uk/gov/hmrc/tai/service/AuditService.scala
=> PAYEE-829: Parallel calls in ExternalServiceRedirectController

app/uk/gov/hmrc/tai/service/YourTaxFreeAmountService.scala
=> PAYEE-852: uses mapN in taxFreeAmountComparison

build.sbt
=> Fixed tests issues

app/views/paye/RtiDisabledHistoricPayAsYouEarnView.scala.html, conf/application.conf, test/views/html/paye/RtiDownHistoricPayAsYouEarnViewSpec.scala
=> PAYEE-877 enable UR banner

app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala, app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala, test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala, test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
=> PAYEE-763: Remove TaiResponse from TaxCodeChangeConnector.taxCodeChange

conf/application.conf
=> PAYEE-983 disable UR banner

app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala, app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala, test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala, test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
=> PAYEE-765 - Removed TaiResponse from taxCodeMismatch

app/views/incomeTaxSummaryIncomeSourceDetail.scala.html, test/views/html/IncomeTaxSummaryViewSpec.scala
=> PAYEE-964: Fix overlapping text & Provide unique ids

app/uk/gov/hmrc/tai/connectors/CompanyCarConnector.scala, test/uk/gov/hmrc/tai/connectors/CompanyCarConnectorSpec.scala
=> PAYEE-915: Removes unused withdrawCompanyCarAndFuel method

app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
=> PAYEE-939: Print button moved to top of PAYE Income Tax and employment history

project/AppDependencies.scala, project/plugins.sbt
This is to avoid bobby violations
=> PAYEE-984: Upgrade tai-frontend libraries to more recent and stable versions

app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, app/views/WhatDoYouWantToDoTileView.scala.html, conf/messages, conf/messages.cy, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> PAYEE-965: Replace tiles with hyperlinks on WDYWTD page

app/controllers/WhatDoYouWantToDoController.scala, app/uk/gov/hmrc/tai/viewModels/WhatDoYouWantToDoViewModel.scala, app/views/WhatDoYouWantToDoTileView.scala.html, conf/messages, conf/messages.cy, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
Reverts hmrc/tai-frontend#1140
=> Revert "PAYEE-965: Replace tiles with hyperlinks on WDYWTD page"

app/assets/stylesheets/tai.scss
=> PAYEE-989 Fix print icon position

app/controllers/employments/UpdateEmploymentController.scala
=> PAYEE-780 - Removing exception and adding error page

app/controllers/IncomeController.scala
=> PAYEE-783 - Fixing NmberFormatException issue

app/views/includes/link.scala.html, test/views/html/incomes/EstimatedPayLandingPageViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1StartViewSpec.scala
=> PAYEE-827: Changed link CSS to match GDS

app/assets/javascripts/backlink.js, app/views/MainTemplate.scala.html
=> PAYEE-1084 - add js file to fix browser back btn issue

app/views/incomes/TaxablePayslipAmountView.scala.html
=> PAYEE-1042: Remove excess comma from taxable pay form title

app/views/incomes/DuplicateSubmissionWarningView.scala.html
=> PAYEE-1033: fixes DuplicateSubmissionWarningView

app/assets/stylesheets/tai.scss, app/views/pensions/AddPensionNumberView.scala.html
=> PAYEE-1025 - Remove bold styling and shrink input box

app/views/WhatDoYouWantToDoTileView.scala.html, test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> PAYE-1114: Remove the tile  from the PAYE landing page

app/views/includes/ptaHeader.scala.html
=> PAYEE-1037-remove-hyphens

app/controllers/IncomeTaxComparisonController.scala, app/uk/gov/hmrc/tai/util/FutureOps.scala, app/views/employments/AddEmploymentPayrollNumberFormView.scala.html, it/controllers/PotentialUnderpaymentControllerErrorHandlingSpec.scala, it/utils/FileHelper.scala, it/utils/IntegrationSpec.scala, it/utils/MockTemplateRenderer.scala, it/utils/WireMockHelper.scala
=> PAYEE-1019: Make payroll number entry field label not bold

app/views/incomeTaxComparison/MainView.scala.html
=> PAYEE-994 - place H1 in two thirds container

app/controllers/WhatDoYouWantToDoController.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala
=> PAYEE-791 - Fixing tax code change bug, see ticket for info

app/controllers/IncomeTaxHistoryController.scala
=> PAYEE-1126: Sequentially call taxCodeIncomes and employmentDetails

app/views/IncomeTaxSummaryView.scala.html
=> PAYEE-1121: Body class added to p tags

conf/application.conf
=> PAYEE-1101 0 enable UR banner and update survey link

app/uk/gov/hmrc/tai/config/FeatureTogglesConfig.scala, test/controllers/IncomeTaxHistoryControllerSpec.scala
=> PAYEE-1134: adds 5 years back to IncomeTaxHistory page

app/assets/stylesheets/tai.scss, app/views/incomes/HistoricIncomeCalculationView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/TaiViewSpec.scala, test/views/html/incomes/HistoricIncomeCalculationViewSpec.scala
=> PAYEE-1157: Amended discrepancy in print button

app/views/incomeTaxComparison/IncomeSummary.scala.html, app/views/incomeTaxComparison/TaxFreeAmount.scala.html
=> PAYEE-1165: Fix Alignment/Spacing issues

app/uk/gov/hmrc/tai/viewModels/IncomeSourceViewModel.scala, app/views/incomeTaxSummaryIncomeSourceDetail.scala.html
=> PAYEE-962: shows tax code and employer reference for ceased employments

app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
=> PAYEE-1136: formats NINO in income tax history

app/views/paye/HistoricPayAsYouEarnView.scala.html, test/views/html/paye/HistoricPayAsYouEarnViewSpec.scala
=> PAYEE 1164: Fix alignment issues on mobile view

app/assets/stylesheets/tai.scss, app/views/TaxFreeAmountView.scala.html
=> PAYEE-1166 fix alignment issue

app/views/incomeTaxComparison/MainView.scala.html
=> Payee 1186

app/assets/stylesheets/tai.scss, app/views/MainTemplate.scala.html
=> PAYEE-1133 - custom js , css to fix language selector 

app/assets/stylesheets/tai.scss
=> disable hiding of banner

app/views/incomes/nextYear/UpdateIncomeCYPlus1ConfirmView.scala.html, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1ConfirmViewSpec.scala
=> PAYEE-1145: Consistent wording for cancel on cy+1 confirmation page

app/uk/gov/hmrc/tai/util/MonetaryUtil.scala, test/controllers/PayeControllerHistoricSpec.scala, test/uk/gov/hmrc/tai/util/MonetaryUtilSpec.scala, test/uk/gov/hmrc/tai/util/ViewModelHelperSpec.scala, test/uk/gov/hmrc/tai/viewModels/PreviousYearUnderpaymentViewModelSpec.scala, test/uk/gov/hmrc/tai/viewModels/TaxSummaryLabelSpec.scala, test/views/html/paye/HistoricPayAsYouEarnViewSpec.scala
=> PAYEE-1137: Remove nil pence

conf/application.conf
=> UrBannerRemoval

conf/messages, conf/messages.cy
=> PAYEE-1208 re-add missing message labels

app/assets/stylesheets/modules/_print.scss
=> PAYEE-1221 - update css to hide UR banner items for print

app/views/TaxFreeAmountView.scala.html, app/views/includes/taxFreeAmountSummary.scala.html
=> PAYEE-1217: Tax free allowance page - vertical alignment

app/assets/stylesheets/modules/tax_code_change.scss
=> PAYEE-1218: Add left-margin to TaxCodeComparisonPage mobile

app/views/IncomeTaxSummaryView.scala.html, app/views/paye/HistoricPayAsYouEarnView.scala.html
=> PAYEE-1215 - add spacing around print links

app/assets/stylesheets/tai.scss, app/views/incomeTaxComparison/IncomeSummary.scala.html
=> PAYEE-1216 UI improvements mobile view table  fix

app/views/WhatDoYouWantToDoTileView.scala.html
=> PAYEE-1271: Swap tiles on WDYWTD page

app/uk/gov/hmrc/tai/model/domain/Address.scala, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, test/controllers/FakeTaiPlayApplication.scala, test/views/html/incomeTaxHistory/IncomeTaxHistoryViewSpec.scala
=> PAYEE-806: Accept empty fields in the Address

app/controllers/benefits/RemoveCompanyBenefitController.scala, app/views/benefits/RemoveCompanyBenefitConfirmationView.scala.html, app/views/includes/confirmationSuccessBanner.scala.html, conf/messages, conf/messages.cy, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala, test/views/html/benefits/RemoveCompanyBenefitConfirmationViewSpec.scala
=> PAYEE-1056: shows dynamic confirmation time

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/MainTemplate.scala.html, conf/application.conf, it/controllers/WhatDoYouWantToDoControllerSpec.scala, project/AppDependencies.scala
=> DDCNL-7397: Webchat implementation

app/views/includes/link.scala.html
=> html errors fixed

app/views/IncomeSourceSummaryView.scala.html, app/views/WhatDoYouWantToDoTileView.scala.html, app/views/includes/ptaHeader.scala.html, app/views/incomes/BonusPaymentAmountView.scala.html, app/views/incomes/BonusPaymentsView.scala.html, app/views/incomes/DuplicateSubmissionWarningView.scala.html, app/views/incomes/EstimatedPayLandingPageView.scala.html, app/views/incomes/HowToUpdateView.scala.html, app/views/incomes/PayPeriodView.scala.html, app/views/incomes/PayslipAmountView.scala.html, app/views/incomes/PayslipDeductionsView.scala.html, app/views/incomes/TaxablePayslipAmountView.scala.html, app/views/incomes/WorkingHoursView.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/views/html/IncomeSourceSummaryViewSpec.scala, test/views/html/incomes/BonusPaymentAmountViewSpec.scala, test/views/html/incomes/BonusPaymentsViewSpec.scala, test/views/html/incomes/HowToUpdateViewSpec.scala, test/views/html/incomes/PayPeriodViewSpec.scala, test/views/html/incomes/PayslipAmountViewSpec.scala, test/views/html/incomes/PayslipDeductionsViewSpec.scala, test/views/html/incomes/TaxablePayslipAmountViewSpec.scala, test/views/html/incomes/WorkingHoursViewSpec.scala
=> journey 3 updated

app/views/benefits/RemoveBenefitTotalValueView.scala.html, app/views/benefits/RemoveCompanyBenefitStopDateView.scala.html, app/views/benefits/UpdateOrRemoveCompanyBenefitDecisionView.scala.html, app/views/includes/taxFreeAmountSummary.scala.html, test/views/html/benefits/RemoveBenefitTotalValueViewSpec.scala, test/views/html/benefits/RemoveCompanyBenefitStopDateViewSpec.scala, test/views/html/benefits/UpdateOrRemoveCompanyBenefitDecisionViewSpec.scala
=> journey 4 updated

app/views/incomeTaxComparison/MainView.scala.html
=> notification banner updated

app/views/incomes/previousYears/UpdateIncomeDetailsDecisionView.scala.html, app/views/incomes/previousYears/UpdateIncomeDetailsView.scala.html, test/views/html/incomes/previousYears/UpdateIncomeDetailsDecisionViewSpec.scala, test/views/html/incomes/previousYears/UpdateIncomeDetailsViewSpec.scala
=> journey 6 updated

app/assets/stylesheets/modules/_description_list.scss, app/views/taxCodeChange/FormattedTaxCodeForComparison.scala.html, test/uk/gov/hmrc/tai/util/viewHelpers/JsoupMatchers.scala, test/views/html/taxCodeChange/TaxCodeComparisonViewSpec.scala
=> tax code change page cleaned up

app/views/pensions/update/DoYouGetThisPensionIncomeView.scala.html, app/views/pensions/update/WhatDoYouWantToTellUsView.scala.html, test/views/html/pensions/DoYouGetThisPensionIncomeViewSpec.scala, test/views/html/pensions/updatePensions/WhatDoYouWantToTellUsViewSpec.scala
=> journey 8 updated

app/views/pensions/AddPensionNameView.scala.html, app/views/pensions/AddPensionNumberView.scala.html, app/views/pensions/AddPensionReceivedFirstPayView.scala.html, app/views/pensions/AddPensionStartDateView.scala.html, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/views/html/pensions/AddPensionNameViewSpec.scala, test/views/html/pensions/AddPensionNumberViewSpec.scala, test/views/html/pensions/AddPensionReceivedFirstPayViewSpec.scala, test/views/html/pensions/AddPensionStartDateViewSpec.scala
=> journey 9 updated

app/controllers/WhatDoYouWantToDoController.scala, it/controllers/WhatDoYouWantToDoControllerSpec.scala, it/utils/IntegrationSpec.scala, it/utils/JsonGenerator.scala, test/controllers/WhatDoYouWantToDoControllerSpec.scala
=> DDCNL-7584 Tax code change banner

app/views/employments/DuplicateSubmissionWarningView.scala.html, app/views/employments/EndEmploymentIrregularPaymentErrorView.scala.html
=> duplicate warning page title updated

app/views/CanWeContactByPhoneView.scala.html, app/views/benefits/RemoveBenefitTotalValueView.scala.html, app/views/employments/AddEmploymentPayrollNumberFormView.scala.html, app/views/employments/AddEmploymentStartDateFormView.scala.html, app/views/employments/EndEmploymentIrregularPaymentErrorView.scala.html, app/views/employments/EndEmploymentView.scala.html, app/views/includes/duplicateSubmissionWarning.scala.html, app/views/incomes/BonusPaymentAmountView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1WarningView.scala.html, app/views/incomes/previousYears/UpdateIncomeDetailsDecisionView.scala.html, app/views/pensions/AddPensionNumberView.scala.html, app/views/pensions/AddPensionStartDateView.scala.html, test/views/html/benefits/RemoveBenefitTotalValueViewSpec.scala, test/views/html/employments/AddEmploymentStartDateFormViewSpec.scala, test/views/html/employments/EndEmploymentViewSpec.scala, test/views/html/incomes/BonusPaymentAmountViewSpec.scala
=> hint text updated on multiple pages

app/views/taxCodeChange/YourTaxFreeAmountView.scala.html, test/views/html/taxCodeChange/YourTaxFreeAmountViewSpec.scala
=> accessibility heading update

project/AppDependencies.scala
=> DDCNL-7903

conf/logback.xml
=> Ddcnl 8056

conf/application.conf
=> DDCNL decrease toggle cache ttl

app/assets/stylesheets/modules/_tax_bar.scss
=> DDCNL-8109: Updated band and tax-free BG color

conf/application.conf
=> disable auditing locally

app/views/MainTemplate.scala
=> DDCNL-8377

app/assets/javascripts/backlink.js, conf/application.conf
=> ur banner text updated

it/controllers/ContentsCheckPertaxBackendToggleOffSpec.scala, it/controllers/ContentsCheckSpec.scala, it/controllers/WhatDoYouWantToDoControllerSpec.scala
=> DDCNL-8409: fixed it:test with change of year

app/views/CanWeContactByPhoneView.scala.html, app/views/benefits/RemoveBenefitTotalValueView.scala.html, app/views/benefits/RemoveCompanyBenefitStopDateView.scala.html, app/views/benefits/UpdateOrRemoveCompanyBenefitDecisionView.scala.html, app/views/employments/AddEmploymentNameFormView.scala.html, app/views/employments/AddEmploymentPayrollNumberFormView.scala.html, app/views/employments/AddEmploymentStartDateFormView.scala.html, app/views/employments/EndEmploymentView.scala.html, app/views/employments/UpdateRemoveEmploymentDecisionView.scala.html, app/views/employments/update/WhatDoYouWantToTellUsView.scala.html, app/views/includes/link.scala.html, app/views/includes/submit.scala.html, app/views/incomes/BonusPaymentAmountView.scala.html, app/views/incomes/BonusPaymentsView.scala.html, app/views/incomes/DuplicateSubmissionWarningView.scala.html, app/views/incomes/EditIncomeIrregularHoursView.scala.html, app/views/incomes/EditIncomeView.scala.html, app/views/incomes/EditPensionView.scala.html, app/views/incomes/EditSuccessView.scala.html, app/views/incomes/HowToUpdateView.scala.html, app/views/incomes/PayPeriodView.scala.html, app/views/incomes/PayslipAmountView.scala.html, app/views/incomes/PayslipDeductionsView.scala.html, app/views/incomes/TaxablePayslipAmountView.scala.html, app/views/incomes/WorkingHoursView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1SuccessView.scala.html, app/views/pensions/update/DoYouGetThisPensionIncomeView.scala.html, project/plugins.sbt
=> id added to submit buttons

app/assets/javascripts/backlink.js, app/views/MainTemplate.scala
=> DDCNL-8503 Turning off banner and removing JS workaround

project/AppDependencies.scala
=> [DDCNL-8577]Updated sca-wrapper to 1.3.0

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/estimatedIncomeTax/taxBandTable.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/views/html/estimatedIncomeTax/DetailedIncomeTaxEstimateViewSpec.scala
=> DDCNL-8746 Removed Z23 timer toggle

app/views/includes/taxFreeAmountSummary.scala.html
Fix alignment of columns in /check-income-tax/tax-free-allowance
=> DDCNL-8942: cya actions column class fixed

app/views/InternalServerErrorView.scala.html, app/views/ManualCorrespondenceView.scala.html, app/views/WhatDoYouWantToDoTileView.scala.html, app/views/includes/checkYourAnswers.scala.html, app/views/includes/iFormInProgressBanner.scala.html, app/views/includes/link.scala.html, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, app/views/incomes/ConfirmAmountEnteredView.scala.html, app/views/incomes/EstimatedPayLandingPageView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1ConfirmView.scala.html, test/uk/gov/hmrc/tai/config/ErrorHandlerSpec.scala, test/uk/gov/hmrc/tai/viewModels/estimatedIncomeTax/SimpleEstimatedIncomeTaxViewModelSpec.scala
=> link styles corrected

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/WhatDoYouWantToDoTileView.scala.html, conf/application.conf, test/views/html/WhatDoYouWantToDoTileViewSpec.scala
=> [DDCNL-9312]TES - Remove the Employee expenses link

conf/application.conf
=> removed unused template provider config

build.sbt, project/AppDependencies.scala, test/controllers/income/estimatedPay/update/IncomeUpdateBonusControllerSpec.scala
=> DDCNL-9670 Updated libraries + footer crown logo

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/MainTemplate.scala
=> DDCNL-9799 Remove referrer from accessibility statement

README.md, app/testOnly/controllers/ApiCallController.scala, conf/testOnlyDoNotUseInAppConf.routes
=> Ddcnl 9708 b

app/views/IncomeSourceSummaryView.scala.html, app/views/incomeTaxHistory/IncomeTaxHistoryView.scala.html, app/views/incomes/HowToUpdateView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1ConfirmView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1EditView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1SameView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1StartView.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1Template.scala.html, app/views/incomes/nextYear/UpdateIncomeCYPlus1WarningView.scala.html, project/AppDependencies.scala, project/plugins.sbt, test/views/html/incomes/HowToUpdateViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1ConfirmViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1EditViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1SameViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1StartViewSpec.scala, test/views/html/incomes/nextYear/UpdateIncomeCYPlus1WarningViewSpec.scala
=> DDCNL-9928

app/views/incomeTaxComparison/MainView.scala.html, test/views/html/incomeTaxComparison/MainViewSpec.scala
=> DDCNL-10047 Remove hardcode backlink from income-tax-comparison

app/repository/JourneyCacheRepository.scala, it/test/controllers/ContentsCheckSpec.scala
=> fixed test due to new tax year, fix loss of mdc context

app/controllers/ServiceController.scala, conf/application.conf, test/controllers/ServiceControllerSpec.scala
=> 10363 Implement as per ticket

app/controllers/auth/AuthRetrievals.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/connectors/FandFConnector.scala, build.sbt, conf/application.conf, it/resources/trustedHelperDetails.json, it/test/controllers/ContentsCheckSpec.scala, it/test/controllers/PotentialUnderpaymentControllerErrorHandlingSpec.scala, it/test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/controllers/auth/AuthRetrievalsSpec.scala, test/uk/gov/hmrc/tai/connectors/FandFConnectorSpec.scala
=> Ddcnl 10234

app/uk/gov/hmrc/tai/service/benefits/BenefitsService.scala, test/controllers/benefits/RemoveCompanyBenefitControllerSpec.scala, test/uk/gov/hmrc/tai/service/benefits/BenefitsServiceSpec.scala
=> tai-frontend: fallback when get benefits returns 404

app/controllers/auth/AuthRetrievals.scala, app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/uk/gov/hmrc/tai/connectors/FandFConnector.scala, build.sbt, conf/application.conf, it/resources/trustedHelperDetails.json, it/test/controllers/ContentsCheckSpec.scala, it/test/controllers/PotentialUnderpaymentControllerErrorHandlingSpec.scala, it/test/controllers/WhatDoYouWantToDoControllerSpec.scala, test/controllers/auth/AuthRetrievalsSpec.scala, test/uk/gov/hmrc/tai/connectors/FandFConnectorSpec.scala
This reverts commit 30d5ebedf6c31895f1c27a243a40b5db169e04ca.
=> Revert "Revert "Ddcnl 10234 (#1364)""

app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
=> DDCNL-10607

app/uk/gov/hmrc/tai/config/ApplicationConfig.scala, app/views/TaxFreeAmountView.scala.html, conf/messages, conf/messages.cy, test/views/html/TaxFreeAmountViewSpec.scala
=> DDCNL-10528: Updated content for tax-free-allowance page something missing section

app/assets/stylesheets/tai.scss, app/views/benefits/CompanyBenefitsView.scala.html
=> DDCNL-10917: Fix company benefits page table content appears stretched issue

app/controllers/BeforeYouStartController.scala, app/controllers/employments/AddEmploymentController.scala, app/controllers/pensions/AddPensionProviderController.scala, app/pages/AddPayeRefPage.scala, app/uk/gov/hmrc/tai/forms/PayeRefForm.scala, app/uk/gov/hmrc/tai/model/domain/AddPensionProvider.scala, app/uk/gov/hmrc/tai/model/domain/Employment.scala, app/uk/gov/hmrc/tai/viewModels/income/IncomeCheckYourAnswersViewModel.scala, app/uk/gov/hmrc/tai/viewModels/pensions/CheckYourAnswersViewModel.scala, app/views/BeforeYouStart.scala.html, app/views/IncomeTaxSummaryView.scala.html, app/views/employments/PayeRefFormView.scala.html, conf/messages, conf/messages.cy, conf/tai.routes, it/test/controllers/ContentsCheckSpec.scala, test/controllers/BeforeYouStartControllerSpec.scala, test/controllers/employments/AddEmploymentControllerSpec.scala, test/controllers/pensions/AddPensionProviderControllerSpec.scala, test/uk/gov/hmrc/tai/connectors/EmploymentsConnectorSpec.scala, test/uk/gov/hmrc/tai/connectors/PensionProviderConnectorSpec.scala, test/uk/gov/hmrc/tai/forms/PayeRefFormSpec.scala, test/uk/gov/hmrc/tai/model/domain/EmploymentSpec.scala, test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala, test/uk/gov/hmrc/tai/service/PensionProviderServiceSpec.scala, test/uk/gov/hmrc/tai/viewModels/income/IncomeCheckYourAnswersViewModelSpec.scala, test/uk/gov/hmrc/tai/viewModels/pensions/CheckYourAnswersViewModelSpec.scala, test/views/html/BeforeYouStartViewSpec.scala, test/views/html/IncomeTaxSummaryViewSpec.scala, test/views/html/employments/PayeRefFormViewSpec.scala
=> DDCNL-10895
